In [2]:
"""
This notebook configures and runs a fixed-aggregation individual identification experiment
using precomputed audio embeddings. It supports multiple datasets, two embedding backbones,
and two fixed aggregation strategies through a modular configuration block.

Main functionalities
- Sets a global random seed for reproducibility using Lightning.
- Defines dataset, embedding, and output paths relative to the project root.
- Supports two embedding backbones:
    1) BirdNET embeddings extracted from 3 s windows.
    2) Perch embeddings extracted from 5 s windows.
- Supports two fixed aggregation strategies at the vocalization level:
    1) onset: uses the first embedding of each vocalization.
    2) gap: applies global average pooling over all embeddings in the vocalization.
- Loads metadata and embedding parts required for training, validation, and testing.
- Configures logging, metrics, classification reports, and figure output directories.
- Specifies the core model hyperparameters for the downstream classifier.

Supported datasets
- chiffchaff: supports within-year and across-year splits.
- pipit: supports within-year and across-year splits.
- littleowl: supports across-year only.
- littlepenguin: supports within-year only and uses a single metadata CSV.
- kiwi: supports across-year only and uses a single metadata CSV.
- rtbc: supports across-year only and uses a single metadata CSV.

Key configuration variables
- SEED: Random seed used for reproducibility in splitting and training.
- DATASET_NAME: Dataset to use.
- SPLIT_TYPE: Evaluation subset to use. Options depend on the dataset.
- MODEL: Embedding backbone, either "birdnet" or "perch".
- AGGREGATION: Fixed aggregation strategy, either "onset" or "gap".
- EXPERIMENT_TAG: Descriptive tag used to name the current experiment.
- PARENT_DIR: Project root directory used to build all relative paths.

Notes
- In onset mode, only the first embedding of each vocalization is used.
- In gap mode, the embeddings of each vocalization are averaged before classification.
- Ensure that all input directories and metadata files exist before running the notebook.
"""

from lightning import seed_everything
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset
import torch
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    f1_score, recall_score, balanced_accuracy_score, accuracy_score, roc_auc_score
)
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from lightning import Trainer
from lightning.pytorch.loggers import TensorBoardLogger, CSVLogger
from lightning.pytorch.callbacks import ModelCheckpoint, EarlyStopping
from torch import nn
import torch.nn.functional as F
from lightning import LightningModule
import torchmetrics
from torchmetrics.classification import F1Score
import logging
from lightning import LightningDataModule
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import pandas as pd
from collections import Counter



#SEED = 23



SEEDS = [18, 13, 46, 123, 321]
MODELS = ["birdnet", "perch"]
AGGREGATIONS = ["onset", "gap"]



# ---- Dataset / experiment config ----
# DATASET_NAME = "chiffchaff"        # options: "chiffchaff", "pipit", "littleowl", "littlepenguin", "kiwi", "rtbc"
# SPLIT_TYPE = "withinyear"    # options depend on dataset
# MODEL = "birdnet"              # options: "birdnet", "perch"
# AGGREGATION = "onset"          # options: "onset", "gap"

# MODEL = MODEL.lower()
# AGGREGATION = AGGREGATION.lower()

# if MODEL not in {"birdnet", "perch"}:
#     raise ValueError(f"Unknown MODEL: {MODEL}. Use 'birdnet' or 'perch'.")

# if AGGREGATION not in {"onset", "gap"}:
#     raise ValueError(f"Unknown AGGREGATION: {AGGREGATION}. Use 'onset' or 'gap'.")



# ---- Dataset-specific configuration ----
DATASET_CONFIG = {
    # "chiffchaff": {
    #     "metadata_dir": "chiffchaff-fg",
    #     "label_key_col": "wavfilename",
    #     "allowed_splits": {"withinyear", "acrossyear"},
    #     "train_files": {
    #         "withinyear": "chiffchaff-withinyear-fg-trn.csv",
    #         "acrossyear": "chiffchaff-acrossyear-fg-trn.csv",
    #     },
    #     "test_files": {
    #         "withinyear": "chiffchaff-withinyear-fg-tst.csv",
    #         "acrossyear": "chiffchaff-acrossyear-fg-tst.csv",
    #     },
    # },
    # "pipit": {
    #     "metadata_dir": "pipit-fg",
    #     "label_key_col": "wavfilename",
    #     "allowed_splits": {"withinyear", "acrossyear"},
    #     "train_files": {
    #         "withinyear": "pipit-withinyear-fg-trn.csv",
    #         "acrossyear": "pipit-acrossyear-fg-trn.csv",
    #     },
    #     "test_files": {
    #         "withinyear": "pipit-withinyear-fg-tst.csv",
    #         "acrossyear": "pipit-acrossyear-fg-tst.csv",
    #     },
    # },
    # "littleowl": {
    #     "metadata_dir": "littleowl-fg",
    #     "label_key_col": "wavfilename",
    #     "allowed_splits": {"acrossyear"},
    #     "train_files": {
    #         "acrossyear": "littleowl-acrossyear-fg-trn.csv",
    #     },
    #     "test_files": {
    #         "acrossyear": "littleowl-acrossyear-fg-tst.csv",
    #     },
    # },
    # "littlepenguin": {
    #     "metadata_dir": "littlepenguin_metadata",
    #     "label_key_col": "file_name",
    #     "allowed_splits": {"withinyear"},
    #     "train_files": {
    #         "withinyear": "littlepenguin_metadata_corrected.csv",
    #     },
    #     "test_files": {
    #         "withinyear": None,
    #     },
    # },
    # "kiwi": {
    #     "metadata_dir": "KiwiTrimmed",
    #     "label_key_col": "file_name",
    #     "allowed_splits": {"acrossyear"},
    #     "train_files": {
    #         "acrossyear": "kiwi_metadata.csv",
    #     },
    #     "test_files": {
    #         "acrossyear": None,
    #     },
    # },
    "rtbc": {
        "metadata_dir": "rtbc_metadata",
        "label_key_col": "file_name",
        "allowed_splits": {"acrossyear"},
        "train_files": {
            "acrossyear": "rtbc_metadata.csv",
        },
        "test_files": {
            "acrossyear": None,
        },
    },
}




# if DATASET_NAME not in DATASET_CONFIG:
#     raise ValueError(
#         f"Unknown DATASET_NAME: {DATASET_NAME}. "
#         f"Choose from {list(DATASET_CONFIG.keys())}."
#     )

# cfg = DATASET_CONFIG[DATASET_NAME]

# if SPLIT_TYPE not in cfg["allowed_splits"]:
#     raise ValueError(
#         f"Dataset '{DATASET_NAME}' does not support split '{SPLIT_TYPE}'. "
#         f"Allowed splits: {sorted(cfg['allowed_splits'])}"
#     )

# ---- Model-specific configuration ----

def run_experiment(seed, dataset_name, split_type, model, aggregation):
    SEED = seed
    DATASET_NAME = dataset_name
    SPLIT_TYPE = split_type
    MODEL = model
    AGGREGATION = aggregation

    seed_everything(SEED, workers=True)
    EXPERIMENT_TAG = f"{MODEL}_{AGGREGATION}"
    PARENT_DIR = Path.cwd().parent

    MODEL_CONFIG = {
        "birdnet": {
            "embeddings_dir": "Embeddings_from_3sPadding",
            "embedding_dim": 1024,
        },
        "perch": {
            "embeddings_dir": "Embeddings_from_5sPadding",
            "embedding_dim": 1280,
        },
    }

    model_cfg = MODEL_CONFIG[MODEL]

    # ---- Input paths ----
    PARTS_DIR = (
        PARENT_DIR
        / "Output_files"
        / model_cfg["embeddings_dir"]
        / f"{DATASET_NAME}_parquet_parts"
    )

    METADATA_DIR = PARENT_DIR / "Output_metadata" / cfg["metadata_dir"]
    TRN_CSV = METADATA_DIR / cfg["train_files"][SPLIT_TYPE]

    test_file = cfg["test_files"][SPLIT_TYPE]
    TST_CSV = None if test_file is None else METADATA_DIR / test_file

    # ---- Data columns ----
    LABEL_KEY_COL = cfg["label_key_col"]
    EMB_KEY_COL = "file_name"

    # Optional quick subset of parts (0 = use all)
    LIMIT_N_PARTS = 0

    # ---- Output paths ----
    LOG_ROOT = PARENT_DIR / "logs"
    RUN_NAME = f"{DATASET_NAME}_{SPLIT_TYPE}_{EXPERIMENT_TAG}"
    LOG_DIR = LOG_ROOT / DATASET_NAME / SPLIT_TYPE
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    RESULTS_DIR = PARENT_DIR / "Results" / DATASET_NAME / SPLIT_TYPE
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    METRICS_DIR = RESULTS_DIR / "Metrics"
    METRICS_DIR.mkdir(parents=True, exist_ok=True)

    METRICS_FILE = METRICS_DIR / f"{RUN_NAME}_final_metrics.csv"
    CLASS_REPORT_TXT_FILE = METRICS_DIR / f"{RUN_NAME}_test_classification_report.txt"
    CLASS_REPORT_CSV_FILE = METRICS_DIR / f"{RUN_NAME}_test_classification_report.csv"

    FIGURES_DIR = RESULTS_DIR / f"{RUN_NAME}_figures"
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)

    # ---- Model hyperparameters ----
    EMBEDDING_DIM = model_cfg["embedding_dim"]
    HIDDEN_DIM = 256
    LEARNING_RATE = 1e-3

    print("DATASET_NAME:", DATASET_NAME)
    print("SPLIT_TYPE:", SPLIT_TYPE)
    print("MODEL:", MODEL)
    print("AGGREGATION:", AGGREGATION)
    print("PARTS_DIR:", PARTS_DIR)
    print("TRN_CSV:", TRN_CSV)
    print("TST_CSV:", TST_CSV)
    print("LOG_DIR:", LOG_DIR / RUN_NAME)
    print("METRICS_FILE:", METRICS_FILE)
    print("FIGURES_DIR:", FIGURES_DIR)
    print("EMBEDDING_DIM:", EMBEDDING_DIM)


    # ---- Load available CSVs (train required, test optional) ----
    csv_paths = []
    if 'TRN_CSV' in locals() and TRN_CSV is not None and Path(TRN_CSV).exists():
        csv_paths.append(TRN_CSV)
    if 'TST_CSV' in locals() and TST_CSV is not None and Path(TST_CSV).exists():
        csv_paths.append(TST_CSV)

    if not csv_paths:
        raise ValueError("No label CSVs found. Provide at least TRN_CSV.")

    dfs = [pd.read_csv(p) for p in csv_paths]
    combined_df = pd.concat(dfs, ignore_index=True)

    # ---- Choose schema: single-label vs one-hot ----

    # Case A: single label column present (e.g., 'class')
    SINGLE_LABEL_COLS = [c for c in ["class", "label", "individual_id"] if c in combined_df.columns]

    if SINGLE_LABEL_COLS:
        LABEL_VALUE_COL = SINGLE_LABEL_COLS[0]  # pick the first available
        # Build label column directly
        combined_df["label"] = combined_df[LABEL_VALUE_COL].astype(str)

        # Normalize filenames for robust matching with embeddings
        if LABEL_KEY_COL not in combined_df.columns:
            raise ValueError(f"Missing filename column '{LABEL_KEY_COL}' in label CSV(s).")
        combined_df[LABEL_KEY_COL] = combined_df[LABEL_KEY_COL].astype(str).str.lower()

        combined_labels_dict = dict(zip(combined_df[LABEL_KEY_COL], combined_df["label"]))
        label_keys = set(combined_labels_dict.keys())

        print(f"[Single-label schema] Using '{LABEL_VALUE_COL}' as labels.")
        print(f"Loaded {len(combined_df):,} label rows; unique labeled audio files: {len(label_keys):,}")
        print("Example mapping:", list(combined_labels_dict.items())[:3])

    else:
        # Case B: one-hot schema (your original logic)
        if LABEL_KEY_COL not in combined_df.columns:
            raise ValueError(f"Missing filename column '{LABEL_KEY_COL}' in label CSV(s).")

        indiv_cols = [c for c in combined_df.columns if c != LABEL_KEY_COL]
        if not indiv_cols:
            raise ValueError("No one-hot individual columns found in the labels CSVs.")

        row_sums = combined_df[indiv_cols].sum(axis=1)
        if (row_sums == 0).all():
            raise ValueError("All rows in the one-hot block are zeros; no labeled files detected.")

        # One-hot → single string label: the column name containing the 1
        combined_df["label"] = combined_df[indiv_cols].idxmax(axis=1)

        # Normalize filenames
        combined_df[LABEL_KEY_COL] = combined_df[LABEL_KEY_COL].astype(str).str.lower()

        combined_labels_dict = dict(zip(combined_df[LABEL_KEY_COL], combined_df["label"]))
        label_keys = set(combined_labels_dict.keys())

        print(f"[One-hot schema] Derived labels from one-hot columns (n={len(indiv_cols)}).")
        print(f"Loaded {len(combined_df):,} label rows; unique labeled audio files: {len(label_keys):,}")
        print("Example mapping:", list(combined_labels_dict.items())[:3])

    # Find Parquet parts
    parts = sorted(PARTS_DIR.glob("part_*.parquet"))
    if LIMIT_N_PARTS > 0:
        parts = parts[:LIMIT_N_PARTS]

    if not parts:
        raise FileNotFoundError(f"No parquet parts found in: {PARTS_DIR}")

    print(f"Found {len(parts)} parquet parts; first 3: {[p.name for p in parts[:3]]}")

    # ------------------------------------------------------------------
    # Load labeled embedding rows
    # ------------------------------------------------------------------
    kept_chunks = []

    for part in parts:
        df_part = pd.read_parquet(part)

        if EMB_KEY_COL not in df_part.columns:
            raise ValueError(f"Parquet part {part.name} missing column '{EMB_KEY_COL}'")

        # Normalize filename column for matching
        df_part[EMB_KEY_COL] = (
            df_part[EMB_KEY_COL]
            .astype(str)
            .str.strip()
            .str.lower()
        )

        # Keep only rows whose file appears in the metadata
        df_part = df_part[df_part[EMB_KEY_COL].isin(label_keys)].copy()
        if df_part.empty:
            continue

        # Drop path if present
        if "path" in df_part.columns:
            df_part = df_part.drop(columns=["path"])

        kept_chunks.append(df_part)

    if not kept_chunks:
        raise ValueError("No embeddings matched the labeled filenames.")

    trainvaltest_df = pd.concat(kept_chunks, ignore_index=True)

    # Map labels
    trainvaltest_df["label"] = trainvaltest_df[EMB_KEY_COL].map(combined_labels_dict)

    missing_labels = trainvaltest_df["label"].isna().sum()
    if missing_labels > 0:
        raise ValueError(f"{missing_labels} rows have missing labels after mapping.")

    print(f"Rows before aggregation: {len(trainvaltest_df):,}")
    print(f"Unique files before aggregation: {trainvaltest_df[EMB_KEY_COL].nunique():,}")

    # ------------------------------------------------------------------
    # Apply file-level aggregation
    # ------------------------------------------------------------------
    if AGGREGATION == "onset":
        if "start_time" not in trainvaltest_df.columns:
            raise ValueError("The 'start_time' column is required for onset aggregation.")

        # Sort within each file and keep the first embedding
        trainvaltest_df = (
            trainvaltest_df
            .sort_values(by=[EMB_KEY_COL, "start_time"])
            .groupby([EMB_KEY_COL, "label"], as_index=False)
            .first()
        )

        print("Applied onset aggregation: kept the first embedding per file.")

    elif AGGREGATION == "gap":
        cols_to_group = [EMB_KEY_COL, "label"]

        # Average numeric columns per file
        trainvaltest_df = (
            trainvaltest_df
            .groupby(cols_to_group, as_index=False)
            .mean(numeric_only=True)
        )

        # Drop time columns after pooling if they remain
        cols_to_drop = [c for c in ["start_time", "end_time"] if c in trainvaltest_df.columns]
        if cols_to_drop:
            trainvaltest_df = trainvaltest_df.drop(columns=cols_to_drop)

        print("Applied GAP aggregation: averaged embeddings per file.")

    else:
        raise ValueError(
            f"Unknown AGGREGATION: {AGGREGATION}. Use 'onset' or 'gap'."
        )

    print(f"Rows after aggregation: {len(trainvaltest_df):,}")
    print(f"Unique files after aggregation: {trainvaltest_df[EMB_KEY_COL].nunique():,}")
    print("Final columns:", trainvaltest_df.columns.tolist())
    assert trainvaltest_df[EMB_KEY_COL].nunique() == len(trainvaltest_df), \
        "Aggregation failed: more than one row remains for at least one file."
    # Map file_name → label
    trainvaltest_df["label"] = trainvaltest_df[EMB_KEY_COL].map(combined_labels_dict)

    # (Optional) sanity: any missing labels after mapping?
    missing = trainvaltest_df["label"].isna().sum()
    if missing:
        print(f"Warning: {missing} rows had missing labels after mapping.")

    # Unique file-level table (one row per file with its label)
    file_labels = trainvaltest_df[[EMB_KEY_COL, "label"]].drop_duplicates()

    # 1) 80/20 split (train+val / test)
    train_val_files_only, test_files_only = train_test_split(
        file_labels,
        test_size=0.20,
        stratify=file_labels["label"],
        random_state=SEED+19,
    )

    # 2) Split the 80 into 60/20 (train / val)
    train_files_only, val_files_only = train_test_split(
        train_val_files_only,
        test_size=0.25,  # 25% of 80% → 20% total
        stratify=train_val_files_only["label"],
        random_state=SEED+19,
    )

    # 3) Build final row-level DataFrames by selecting rows for those file sets
    train_df = trainvaltest_df[trainvaltest_df[EMB_KEY_COL].isin(train_files_only[EMB_KEY_COL])].copy()
    val_df   = trainvaltest_df[trainvaltest_df[EMB_KEY_COL].isin(val_files_only[EMB_KEY_COL])].copy()
    test_df  = trainvaltest_df[trainvaltest_df[EMB_KEY_COL].isin(test_files_only[EMB_KEY_COL])].copy()

    train_df = train_df.sort_index()
    val_df   = val_df.sort_index()
    test_df  = test_df.sort_index()

    print(f"Train: {len(train_df):,} rows")
    print(f"Validation: {len(val_df):,} rows")
    print(f"Test: {len(test_df):,} rows")

    print("Labels in TRN:", sorted(train_df["label"].unique()))
    print("Labels in VAL:", sorted(val_df["label"].unique()))
    print("Labels in TST:", sorted(test_df["label"].unique()))

    le = LabelEncoder()

    # Fit on training labels only
    train_df["label"] = le.fit_transform(train_df["label"])

    # Transform val/test consistently
    val_df["label"] = le.transform(val_df["label"])
    test_df["label"] = le.transform(test_df["label"])

    print("Encoded classes:", list(le.classes_))



    def build_pooled_per_file_dicts(df, key_col, dims_cols, label_col):
        """
        Return (embeddings_dict, id_dict, file_list) from a pooled DataFrame.

        Assumes the input DataFrame already contains exactly one aggregated embedding
        vector per file, as produced by onset or GAP aggregation.
        """
        embeddings_dict = {}
        id_dict = {}

        for _, row in df.iterrows():
            file_name = row[key_col]
            vector = row[dims_cols].to_numpy(dtype="float32")  # shape (D,)

            embeddings_dict[file_name] = vector
            id_dict[file_name] = row[label_col]

        files = list(id_dict.keys())
        return embeddings_dict, id_dict, files


    # Identify embedding dimension columns
    dims_cols = [c for c in train_df.columns if c.startswith("dim_")]

    # Train
    audio_train_embeddings, id_train_dict, train_files = build_pooled_per_file_dicts(
        train_df, EMB_KEY_COL, dims_cols, "label"
    )

    # Val
    audio_val_embeddings, id_val_dict, val_files = build_pooled_per_file_dicts(
        val_df, EMB_KEY_COL, dims_cols, "label"
    )

    # Test
    audio_test_embeddings, id_test_dict, test_files = build_pooled_per_file_dicts(
        test_df, EMB_KEY_COL, dims_cols, "label"
    )


    class SubsetAudioDataset(Dataset):
        """
        Return (embedding, label) for a subset of files.

        Parameters
        ----------
        file_list : list
            List of file names belonging to the split.
        audio_embeddings : dict
            Dictionary mapping file_name -> pooled embedding vector of shape (D,).
        file_to_label : dict
            Dictionary mapping file_name -> encoded class label.
        """
        def __init__(self, file_list, audio_embeddings, file_to_label):
            self.file_list = file_list
            self.audio_embeddings = audio_embeddings
            self.file_to_label = file_to_label

        def __len__(self):
            return len(self.file_list)

        def __getitem__(self, idx):
            file_name = self.file_list[idx]
            emb_np = self.audio_embeddings[file_name]  # shape (D,)

            if emb_np.ndim != 1:
                raise ValueError(
                    f"Expected a 1D pooled embedding for file '{file_name}', "
                    f"but got shape {emb_np.shape}"
                )

            embeddings = torch.tensor(emb_np, dtype=torch.float32)  # shape (D,)
            label = torch.tensor(self.file_to_label[file_name], dtype=torch.long)

            return embeddings, label


    # Create datasets
    train_dataset = SubsetAudioDataset(train_files, audio_train_embeddings, id_train_dict)
    val_dataset   = SubsetAudioDataset(val_files,   audio_val_embeddings,  id_val_dict)
    test_dataset  = SubsetAudioDataset(test_files,  audio_test_embeddings, id_test_dict)

    print(f"Train size: {len(train_dataset)}")
    print(f"Validation size: {len(val_dataset)}")
    print(f"Test size: {len(test_dataset)}")


    # --- Count labels in each split ---
    def count_labels(dataset):
        """Count label frequencies in a PyTorch dataset."""
        return Counter(label.item() for _, label in dataset)

    datasets = {
        "train": train_dataset,
        "val": val_dataset,
        "test": test_dataset
    }

    # Create DataFrame with counts
    counts_df = pd.DataFrame({
        split: pd.Series(count_labels(ds))
        for split, ds in datasets.items()
    }).fillna(0).astype(int)

    # --- Sort by frequency in train ---
    counts_df = counts_df.sort_values(by="train", ascending=False)

    # --- Compute totals (not for plotting) ---
    total_per_individual = counts_df.sum(axis=1)

    # --- Metrics ---
    total_vocalizations = int(total_per_individual.sum())
    max_vocalizations   = int(total_per_individual.max())
    min_vocalizations   = int(total_per_individual.min())
    mean_vocalizations  = float(total_per_individual.mean())
    std_vocalizations   = float(total_per_individual.std(ddof=1))  # sample SD

    # --- Display counts DataFrame ---
    display(counts_df)

    # --- Print requested metrics ---
    print("=== Dataset metrics (all splits combined) ===")
    print(f"Total vocalizations: {total_vocalizations}")
    print(f"Maximum vocalizations per individual: {max_vocalizations}")
    print(f"Minimum vocalizations per individual: {min_vocalizations}")
    print(f"Vocalizations per individual (mean ± SD): {mean_vocalizations:.1f} ± {std_vocalizations:.1f}")
    print(f"Vocalizations per individual (mean ± SD, rounded): {round(mean_vocalizations):.0f} ± {round(std_vocalizations):.0f}")

    # --- Plot per-split distribution ---
    # counts_df.plot(kind='bar', figsize=(10, 6))
    # plt.xlabel('Individual (Label)')
    # plt.ylabel('Number of Samples')
    # plt.title('Distribution of Individuals in Train / Validation / Test')
    # plt.legend(title='Dataset')
    # plt.tight_layout()
    # plt.show()




    class PooledEmbeddingDataModule(LightningDataModule):
        def __init__(
            self,
            train_dataset,
            val_dataset,
            test_dataset,
            batch_size: int = 32,
            num_workers: int = 0,              # 0 is safest in notebooks
            pin_memory: bool = False,          # set True if training on GPU
            persistent_workers: bool = False,  # True only if num_workers > 0
            drop_last: bool = False,
        ):
            super().__init__()
            self.train_dataset = train_dataset
            self.val_dataset = val_dataset
            self.test_dataset = test_dataset

            self.batch_size = batch_size
            self.num_workers = num_workers
            self.pin_memory = pin_memory
            self.persistent_workers = persistent_workers if num_workers > 0 else False
            self.drop_last = drop_last

        def _make_loader(self, dataset, shuffle: bool):
            return DataLoader(
                dataset,
                batch_size=self.batch_size,
                shuffle=shuffle,
                num_workers=self.num_workers,
                pin_memory=self.pin_memory,
                persistent_workers=self.persistent_workers,
                drop_last=self.drop_last,
            )

        def train_dataloader(self):
            return self._make_loader(self.train_dataset, shuffle=True)

        def val_dataloader(self):
            return self._make_loader(self.val_dataset, shuffle=False)

        def test_dataloader(self):
            return self._make_loader(self.test_dataset, shuffle=False)


    use_cuda = torch.cuda.is_available()

    data_module = PooledEmbeddingDataModule(
        train_dataset,
        val_dataset,
        test_dataset,
        batch_size=32,
        num_workers=0,
        pin_memory=use_cuda,
        persistent_workers=False,
        drop_last=False,
    )


    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)


    class BirdsongClassifier(LightningModule):
        """
        Fully connected classifier for fixed-size embedding vectors of shape (B, D).
        """

        def __init__(
            self,
            embedding_dim: int,
            hidden_dim: int,
            num_classes: int,
            lr: float = 1e-3,
            dropout: float = 0.0,
            class_weights: torch.Tensor | None = None,
        ):
            super().__init__()
            self.save_hyperparameters(ignore=["class_weights"])
            self.class_weights = class_weights

            self.net = nn.Sequential(
                nn.Linear(embedding_dim, hidden_dim),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(hidden_dim, num_classes),
            )

            self.train_accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)
            self.val_accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)
            self.test_accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)

            self.val_f1 = torchmetrics.F1Score(
                task="multiclass",
                num_classes=num_classes,
                average="macro",
            )
            self.test_f1 = torchmetrics.F1Score(
                task="multiclass",
                num_classes=num_classes,
                average="macro",
            )

            self.criterion = nn.CrossEntropyLoss(weight=None)

        def setup(self, stage=None):
            if self.class_weights is not None:
                self.criterion = nn.CrossEntropyLoss(weight=self.class_weights.to(self.device))

        @staticmethod
        def _unpack_batch(batch):
            """
            Support both (x, y) and legacy (x, lengths, y) batches.
            Lengths are ignored for the FCN model.
            """
            if isinstance(batch, (list, tuple)):
                if len(batch) == 2:
                    x, y = batch
                    return x, y
                if len(batch) == 3:
                    x, _, y = batch
                    return x, y
            raise ValueError("Expected batch as (x, y) or (x, lengths, y)")

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            logits = self.net(x)  # (B, C)
            return logits

        def _shared_step(self, batch, stage: str):
            x, y = self._unpack_batch(batch)
            logits = self(x)
            loss = self.criterion(logits, y)

            if stage == "train":
                acc = self.train_accuracy(logits, y)
                self.log("train_loss", loss, prog_bar=True)
                self.log("train_acc", acc, prog_bar=True)
                return loss

            if stage == "val":
                acc = self.val_accuracy(logits, y)
                f1 = self.val_f1(logits, y)
                self.log("val_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
                self.log("val_acc", acc, prog_bar=True, on_step=False, on_epoch=True)
                self.log("val_f1", f1, prog_bar=True, on_step=False, on_epoch=True)
                return loss

            if stage == "test":
                acc = self.test_accuracy(logits, y)
                f1 = self.test_f1(logits, y)
                self.log("test_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
                self.log("test_acc", acc, prog_bar=True, on_step=False, on_epoch=True)
                self.log("test_f1", f1, prog_bar=True, on_step=False, on_epoch=True)
                return loss

            raise ValueError(f"Unknown stage: {stage}")

        def training_step(self, batch, batch_idx):
            loss = self._shared_step(batch, stage="train")
            logger.info(f"Batch {batch_idx} - Train Loss: {loss.item():.4f}")
            return loss

        def validation_step(self, batch, batch_idx):
            self._shared_step(batch, stage="val")

        def test_step(self, batch, batch_idx):
            loss = self._shared_step(batch, stage="test")
            logger.info(f"Batch {batch_idx} - Test Loss: {loss.item():.4f}")

        def configure_optimizers(self):
            return torch.optim.Adam(self.parameters(), lr=self.hparams.lr)
    all_labels = (
        list(id_train_dict.values()) +
        list(id_val_dict.values()) +
        list(id_test_dict.values())
    )

    model = BirdsongClassifier(
        embedding_dim=EMBEDDING_DIM,
        hidden_dim=HIDDEN_DIM,
        num_classes=len(set(all_labels)),  # Adjusted based on label encoder
        lr=LEARNING_RATE
    )



    # Save the best model (by val_f1) and also keep the last checkpoint
    checkpoint_callback = ModelCheckpoint(
        monitor="val_f1",
        mode="max",
        save_top_k=1,
        save_last=True,
        filename=f"best-{DATASET_NAME}-{SPLIT_TYPE}-{EXPERIMENT_TAG}-{{epoch:02d}}-{{val_f1:.4f}}"
        # auto_insert_metric_name=False,  # uncomment if you don't want Lightning to append metric names
    )

    # Early stopping if validation doesn't improve
    early_stop_callback = EarlyStopping(
        monitor="val_f1",
        mode="max",
        patience=10,
        min_delta=1e-4,
    )



    # TensorBoard + CSV under: logs/<DATASET_NAME>/<SPLIT_TYPE>/<RUN_NAME>/version_x/
    tb_logger = TensorBoardLogger(
        save_dir=str(LOG_DIR),   # logs/<DATASET_NAME>/<SPLIT_TYPE>
        name=RUN_NAME,           # <DATASET_NAME>_<SPLIT_TYPE>_RNN
    )

    csv_logger = CSVLogger(
        save_dir=str(LOG_DIR),   # same root, same run name
        name=RUN_NAME,
    )

    trainer = Trainer(
        max_epochs=40,
        accelerator="auto",
        devices="auto",
        callbacks=[checkpoint_callback, early_stop_callback],
        logger=[tb_logger, csv_logger],
        log_every_n_steps=10,
        # Reproducibility and stability (safe defaults)
        deterministic=True,        # ensures repeatable results (may be slightly slower)
        # precision="16-mixed",    # optional: speed-up on GPU; leave commented to keep numerics identical
    )

    trainer.fit(model, datamodule=data_module)


    # Find the latest version directory created by the loggers
    run_dir = LOG_DIR / RUN_NAME
    version_dirs = sorted([p for p in run_dir.glob("version_*") if p.is_dir()],
                        key=lambda p: int(p.name.split("_")[-1]))
    if not version_dirs:
        raise FileNotFoundError(f"No version_* folders found under {run_dir}")
    latest = version_dirs[-1]
    metrics_csv = latest / "metrics.csv"
    print("Reading metrics from:", metrics_csv)

    df = pd.read_csv(metrics_csv)

    # Helper: pick the x-axis. Prefer 'step' if present, else 'epoch' (falls back to index).
    x = df["step"] if "step" in df.columns else (df["epoch"] if "epoch" in df.columns else df.index)

    # Filter rows that actually contain each metric
    df_train_loss = df[df["train_loss"].notna()] if "train_loss" in df.columns else pd.DataFrame()
    df_val_loss   = df[df["val_loss"].notna()]   if "val_loss"   in df.columns else pd.DataFrame()
    df_train_acc  = df[df["train_acc"].notna()]  if "train_acc"  in df.columns else pd.DataFrame()
    df_val_acc    = df[df["val_acc"].notna()]    if "val_acc"    in df.columns else pd.DataFrame()

    # ---- Plot 1: Train vs Validation Loss ----
    # plt.figure(figsize=(8, 5))
    # if not df_train_loss.empty:
    #     plt.plot(df_train_loss["step"] if "step" in df_train_loss else df_train_loss.index,
    #             df_train_loss["train_loss"], label="Train Loss")
    # if not df_val_loss.empty:
    #     plt.plot(df_val_loss["step"] if "step" in df_val_loss else df_val_loss.index,
    #             df_val_loss["val_loss"], label="Validation Loss")
    # plt.xlabel("Step")
    # plt.ylabel("Loss")
    # plt.title("Training & Validation Loss")
    # plt.legend()
    # plt.grid(True, linestyle="--", alpha=0.5)
    # plt.tight_layout()
    # plt.show()

    # ---- Plot 2: Train vs Validation Accuracy ----
    # plt.figure(figsize=(8, 5))
    # if not df_train_acc.empty:
    #     plt.plot(df_train_acc["step"] if "step" in df_train_acc else df_train_acc.index,
    #             df_train_acc["train_acc"], label="Train Accuracy")
    # if not df_val_acc.empty:
    #     plt.plot(df_val_acc["step"] if "step" in df_val_acc else df_val_acc.index,
    #             df_val_acc["val_acc"], label="Validation Accuracy")
    # plt.xlabel("Step")
    # plt.ylabel("Accuracy")
    # plt.title("Training & Validation Accuracy")
    # plt.legend()
    # plt.grid(True, linestyle="--", alpha=0.5)
    # plt.tight_layout()
    # plt.show()

    trainer.test(model, datamodule=data_module)
    # Load the best model (optional)
    best_model_path = checkpoint_callback.best_model_path
    print(f"Best model saved at: {best_model_path}")

    # Alternative: load a specific checkpoint manually
    # best_model_path = "KiWi_logs/individual_identification/version_3/checkpoints/best-individual-identification-KiWi.ckpt"

    best_model = BirdsongClassifier.load_from_checkpoint(best_model_path)
    best_model.eval()
    # Evaluate the best model on the test set
    results = trainer.test(best_model, datamodule=data_module)

    # Print all metrics in a nice format
    print("\nTest Metrics:")
    for metric, value in results[0].items():
        print(f"{metric}: {value:.4f} ({value*100:.1f}%)" if "acc" in metric or "f1" in metric else f"{metric}: {value:.4f}")

    test_acc = results[0]['test_acc']  



    # Load best checkpoint (if not already loaded)
    best_model = BirdsongClassifier.load_from_checkpoint(best_model_path)
    best_model.eval()

    # Put model on the right device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    best_model.to(device)

    all_preds, all_labels = [], []

    # Iterate over the test loader
    with torch.no_grad():
        for x, y in data_module.test_dataloader():  # <-- only (x, y) now
            x = x.to(device)
            y = y.to(device)

            logits = best_model(x)                  # <-- no lengths
            preds = torch.argmax(logits, dim=1)

            all_preds.append(preds.cpu().numpy())
            all_labels.append(y.cpu().numpy())
            
    y_true = np.concatenate(all_labels)
    y_pred = np.concatenate(all_preds)

    # Map class indices -> original string labels from your LabelEncoder
    labels = list(range(len(le.classes_)))
    target_names = [str(c) for c in le.classes_]

    report_text = classification_report(
        y_true,
        y_pred,
        labels=labels,
        target_names=target_names,
        digits=3,
        zero_division=0,   # avoids warnings if a class has no predicted samples
    )

    print(report_text)

    # save the report alongside TensorBoard logs
    with open(CLASS_REPORT_TXT_FILE, "w") as f:
        f.write(report_text)
    print(f"\nSaved classification report (txt) to: {CLASS_REPORT_TXT_FILE}")


    # Dictionary report for CSV export
    report_dict = classification_report(
        y_true,
        y_pred,
        labels=labels,
        target_names=target_names,
        digits=4,
        output_dict=True
    )
    report_df = pd.DataFrame(report_dict).transpose()

    # Optional: keep only per-individual rows
    per_class_report_df = report_df.loc[list(le.classes_)].reset_index()
    per_class_report_df = per_class_report_df.rename(columns={"index": "individual"})

    per_class_report_df.to_csv(CLASS_REPORT_CSV_FILE, index=False)

    print(f"Saved classification report (csv) to: {CLASS_REPORT_CSV_FILE}")
    display(per_class_report_df.head())



    def evaluate_split(model, loader, le, split_name: str):
        """Evaluate a model on a dataloader and compute multiple metrics."""
        model.eval()
        device = next(model.parameters()).device

        all_preds, all_labels, all_logits = [], [], []

        with torch.no_grad():
            for x, y in loader:                         # CHANGED: (x, y)
                x = x.to(device)
                y = y.to(device)

                logits = model(x)                       # CHANGED: model(x)
                preds = torch.argmax(logits, dim=1)

                all_logits.append(logits.detach().cpu().numpy())
                all_preds.append(preds.detach().cpu().numpy())
                all_labels.append(y.detach().cpu().numpy())

        # Arrays
        y_true = np.concatenate(all_labels)
        y_pred = np.concatenate(all_preds)
        logits_np = np.concatenate(all_logits, axis=0)

        # Confusion matrix (plot)
        labels = list(range(len(le.classes_)))
        # cm = confusion_matrix(y_true, y_pred, labels=labels)
        # fig, ax = plt.subplots(figsize=(8, 6))
        # ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_).plot(
        #     ax=ax, xticks_rotation=45, cmap="Blues", colorbar=True
        # )
        # ax.set_title(f"Confusion Matrix — {split_name}")
        # plt.tight_layout()
        # plt.show()

        # Metrics
        acc = accuracy_score(y_true, y_pred)
        acc_bal = balanced_accuracy_score(y_true, y_pred)
        recall_macro    = recall_score(y_true, y_pred, labels=labels, average="macro",    zero_division=0)
        recall_weighted = recall_score(y_true, y_pred, labels=labels, average="weighted", zero_division=0)
        f1_macro        = f1_score(y_true, y_pred,     labels=labels, average="macro",    zero_division=0)
        f1_weighted     = f1_score(y_true, y_pred,     labels=labels, average="weighted", zero_division=0)

        # ROC AUC (macro)
        num_classes = len(np.unique(y_true))
        y_true_bin = label_binarize(y_true, classes=np.arange(num_classes))
        probs = torch.softmax(torch.tensor(logits_np), dim=1).numpy()
        roc_auc_macro = roc_auc_score(y_true_bin, probs, average="macro", multi_class="ovr")

        # Print and return
        print(f"{split_name} — Accuracy:          {acc:.4f} ({acc*100:.1f}%)")
        print(f"{split_name} — Balanced accuracy: {acc_bal:.4f} ({acc_bal*100:.1f}%)")
        print(f"{split_name} — Recall (macro):    {recall_macro:.4f}")
        print(f"{split_name} — Recall (weighted): {recall_weighted:.4f}")
        print(f"{split_name} — F1 (macro):        {f1_macro:.4f} ({f1_macro*100:.1f}%)")
        print(f"{split_name} — F1 (weighted):     {f1_weighted:.4f}")
        print(f"{split_name} — ROC AUC (macro):   {roc_auc_macro:.4f}\n")

        return {
            "accuracy": acc,
            "balanced_accuracy": acc_bal,
            "recall_macro": recall_macro,
            "recall_weighted": recall_weighted,
            "f1_macro": f1_macro,
            "f1_weighted": f1_weighted,
            "roc_auc_macro": roc_auc_macro,
        }


    # Ensure the model is on the right device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    best_model.to(device)

    # Evaluate and collect metrics
    val_metrics  = evaluate_split(best_model, data_module.val_dataloader(),  le, "Validation")
    test_metrics = evaluate_split(best_model, data_module.test_dataloader(), le, "Test")

    summary_row = {
        "run_name": RUN_NAME,
        "seed": SEED,
        "dataset_name": DATASET_NAME,
        "split_type": SPLIT_TYPE,
        "model": MODEL,
        "aggegration": AGGREGATION,
        "embedding_dim": EMBEDDING_DIM,
        "hidden_dim": HIDDEN_DIM,
        "learning_rate": LEARNING_RATE,

        "val_accuracy": val_metrics["accuracy"],
        "val_balanced_accuracy": val_metrics["balanced_accuracy"],
        "val_recall_macro": val_metrics["recall_macro"],
        "val_recall_weighted": val_metrics["recall_weighted"],
        "val_f1_macro": val_metrics["f1_macro"],
        "val_f1_weighted": val_metrics["f1_weighted"],
        "val_roc_auc_macro": val_metrics["roc_auc_macro"],

        "test_accuracy": test_metrics["accuracy"],
        "test_balanced_accuracy": test_metrics["balanced_accuracy"],
        "test_recall_macro": test_metrics["recall_macro"],
        "test_recall_weighted": test_metrics["recall_weighted"],
        "test_f1_macro": test_metrics["f1_macro"],
        "test_f1_weighted": test_metrics["f1_weighted"],
        "test_roc_auc_macro": test_metrics["roc_auc_macro"],
    }

    new_row_df = pd.DataFrame([summary_row])

    key_cols = ["run_name", "seed"]

    if METRICS_FILE.exists():
        metrics_df = pd.read_csv(METRICS_FILE)

        missing_cols = [c for c in key_cols if c not in metrics_df.columns]
        if missing_cols:
            raise ValueError(
                f"Missing key columns in existing metrics file: {missing_cols}"
            )

        mask = pd.Series(True, index=metrics_df.index)
        for col in key_cols:
            mask &= metrics_df[col] == summary_row[col]

        if mask.any():
            metrics_df = metrics_df.loc[~mask].copy()
            action = "updated"
        else:
            action = "appended"

        metrics_df = pd.concat([metrics_df, new_row_df], ignore_index=True)

    else:
        metrics_df = new_row_df.copy()
        action = "created"

    metrics_df = metrics_df.sort_values(by=key_cols).reset_index(drop=True)
    metrics_df.to_csv(METRICS_FILE, index=False)

    print(f"Metrics file {action}: {METRICS_FILE}")
    display(metrics_df)
    # ------------------------------------------------------------------
    # Aggregate summary over all seeds currently stored in METRICS_FILE
    # ------------------------------------------------------------------
    metrics_df = pd.read_csv(METRICS_FILE)

    metric_cols = ["test_accuracy", "test_f1_macro", "test_roc_auc_macro"]
    missing_metric_cols = [c for c in metric_cols if c not in metrics_df.columns]
    if missing_metric_cols:
        raise ValueError(f"Missing metric columns in metrics file: {missing_metric_cols}")

    aggregate_summary = {
        "dataset_name": metrics_df["dataset_name"].iloc[0],
        "split_type": metrics_df["split_type"].iloc[0],
        "model": metrics_df["model"].iloc[0],
        "aggegration_mode": metrics_df["aggegration"].iloc[0],
        "embedding_dim": metrics_df["embedding_dim"].iloc[0],
        "n_seeds": metrics_df["seed"].nunique(),

        "test_accuracy": f"{metrics_df['test_accuracy'].mean():.3f} ± {metrics_df['test_accuracy'].std(ddof=1):.3f}",
        "test_f1_macro": f"{metrics_df['test_f1_macro'].mean():.3f} ± {metrics_df['test_f1_macro'].std(ddof=1):.3f}",
        "test_roc_auc_macro": f"{metrics_df['test_roc_auc_macro'].mean():.4f} ± {metrics_df['test_roc_auc_macro'].std(ddof=1):.4f}",
    }

    aggregate_summary_df = pd.DataFrame([aggregate_summary])

    print("\nAggregate summary across seeds:")
    display(aggregate_summary_df)

for DATASET_NAME, cfg in DATASET_CONFIG.items():
    for SPLIT_TYPE in cfg["allowed_splits"]:
        for MODEL in MODELS:
            for AGGREGATION in AGGREGATIONS:
                for SEED in SEEDS:
                    run_experiment(
                        seed=SEED,
                        dataset_name=DATASET_NAME,
                        split_type=SPLIT_TYPE,
                        model=MODEL,
                        aggregation=AGGREGATION,
                    )

Seed set to 18

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'start_time', 'end_time', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_1/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7595635652542114     │
│         test_loss         │    0.11522399634122849    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_0/checkpoints/best-rtbc-acrossyear-birdnet_onset-epoch=05-val_f1=0.7511.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.6749309301376343     │
│         test_loss         │    0.1959298551082611     │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1959
test_acc: 0.9552 (95.5%)
test_f1: 0.6749 (67.5%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.900     0.947     0.923        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      0.000     0.000     0.000         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     1.000     1.000         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      0.800     0.800     0.800         5
     LS2_2022-23      0.986     0.909     0.946        77
     LS3_2022-23      0.938     0.984     0.961        62
     LS6_2022-23      1.000     0.978     0.989        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      0.848     0.966     0.903        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.955       357
       macro avg      0.889     0.889     0.886       357
    weighted avg      0.953     0.955     0.953       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.900000  0.947368  0.923077     19.0
1  32PC1_2022-23   1.000000  1.000000  1.000000     22.0
2     AL_2019-20   0.000000  0.000000  0.000000      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  1.000000  1.000000      6.0

Validation — Accuracy:          0.9496 (95.0%)
Validation — Balanced accuracy: 0.8706 (87.1%)
Validation — Recall (macro):    0.8706
Validation — Recall (weighted): 0.9496
Validation — F1 (macro):        0.8776 (87.8%)
Validation — F1 (weighted):     0.9477
Validation — ROC AUC (macro):   0.9979

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.8892 (88.9%)
Test — Recall (macro):    0.8892
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.8860 (88.6%)
Test — F1 (weighted):     0.9527
Test — ROC AUC (macro):   0.9993

Metrics file created: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_onset,18,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.94958,...,0.877584,0.94771,0.99792,0.955182,0.889155,0.889155,0.955182,0.88595,0.952678,0.999303

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,onset,1024,1,0.955 ± nan,0.886 ± nan,0.9993 ± nan

Seed set to 13

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'start_time', 'end_time', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_3/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.8127990365028381     │
│         test_loss         │    0.09961488097906113    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_2/checkpoints/best-rtbc-acrossyear-birdnet_onset-epoch=08-val_f1=0.7656.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9719887971878052     │
│          test_f1          │    0.7677643895149231     │
│         test_loss         │    0.12641286849975586    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1264
test_acc: 0.9720 (97.2%)
test_f1: 0.7678 (76.8%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      0.952     0.909     0.930        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.962     0.987     0.974        77
     LS3_2022-23      0.984     0.984     0.984        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      0.976     0.976     0.976        42
     PC3_2022-23      0.966     0.966     0.966        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.913     0.955     0.933        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.972       357
       macro avg      0.983     0.966     0.974       357
    weighted avg      0.972     0.972     0.972       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   1.000000  1.000000  1.000000     19.0
1  32PC1_2022-23   0.952381  0.909091  0.930233     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   1.000000  0.833333  0.909091      6.0

Validation — Accuracy:          0.9664 (96.6%)
Validation — Balanced accuracy: 0.9315 (93.2%)
Validation — Recall (macro):    0.9315
Validation — Recall (weighted): 0.9664
Validation — F1 (macro):        0.9386 (93.9%)
Validation — F1 (weighted):     0.9661
Validation — ROC AUC (macro):   0.9998

Test — Accuracy:          0.9720 (97.2%)
Test — Balanced accuracy: 0.9664 (96.6%)
Test — Recall (macro):    0.9664
Test — Recall (weighted): 0.9720
Test — F1 (macro):        0.9740 (97.4%)
Test — F1 (weighted):     0.9718
Test — ROC AUC (macro):   0.9982

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_onset,13,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_onset,18,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,onset,1024,2,0.964 ± 0.012,0.930 ± 0.062,0.9987 ± 0.0008

Seed set to 46

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'start_time', 'end_time', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_5/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9691876769065857     │
│          test_f1          │    0.7935192584991455     │
│         test_loss         │    0.0993865430355072     │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_4/checkpoints/best-rtbc-acrossyear-birdnet_onset-epoch=12-val_f1=0.7819.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7728484272956848     │
│         test_loss         │    0.11982722580432892    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1198
test_acc: 0.9636 (96.4%)
test_f1: 0.7728 (77.3%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     0.955     0.977        22
      AL_2019-20      1.000     0.500     0.667         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      0.857     1.000     0.923         6
FOURBIRD_2021-22      0.875     0.875     0.875         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.917     1.000     0.957        77
     LS3_2022-23      0.967     0.952     0.959        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.952     0.976        42
     PC3_2022-23      1.000     0.897     0.945        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      1.000     1.000     1.000        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.964       357
       macro avg      0.971     0.923     0.939       357
    weighted avg      0.966     0.964     0.963       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.950000  1.000000  0.974359     19.0
1  32PC1_2022-23   1.000000  0.954545  0.976744     22.0
2     AL_2019-20   1.000000  0.500000  0.666667      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   0.857143  1.000000  0.923077      6.0

Validation — Accuracy:          0.9608 (96.1%)
Validation — Balanced accuracy: 0.9428 (94.3%)
Validation — Recall (macro):    0.9428
Validation — Recall (weighted): 0.9608
Validation — F1 (macro):        0.9528 (95.3%)
Validation — F1 (weighted):     0.9602
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9636 (96.4%)
Test — Balanced accuracy: 0.9234 (92.3%)
Test — Recall (macro):    0.9234
Test — Recall (weighted): 0.9636
Test — F1 (macro):        0.9394 (93.9%)
Test — F1 (weighted):     0.9630
Test — ROC AUC (macro):   0.9996

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_onset,13,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_onset,18,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_onset,46,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,onset,1024,3,0.964 ± 0.008,0.933 ± 0.044,0.9990 ± 0.0007

Seed set to 123

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'start_time', 'end_time', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=40` reached.

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_7/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.7991259694099426     │
│         test_loss         │    0.07716686278581619    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_6/checkpoints/best-rtbc-acrossyear-birdnet_onset-epoch=30-val_f1=0.9384.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.7991259694099426     │
│         test_loss         │    0.07332269102334976    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0733
test_acc: 0.9748 (97.5%)
test_f1: 0.7991 (79.9%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     0.800     0.889         5
     LS2_2022-23      0.962     0.974     0.968        77
     LS3_2022-23      0.984     0.968     0.976        62
     LS6_2022-23      0.978     1.000     0.989        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      0.933     0.966     0.949        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.975       357
       macro avg      0.985     0.962     0.972       357
    weighted avg      0.975     0.975     0.975       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22       0.95  1.000000  0.974359     19.0
1  32PC1_2022-23       1.00  1.000000  1.000000     22.0
2     AL_2019-20       1.00  1.000000  1.000000      2.0
3     AL_2021-22       1.00  1.000000  1.000000      5.0
4    BUG_2021-22       1.00  0.833333  0.909091      6.0

Validation — Accuracy:          0.9916 (99.2%)
Validation — Balanced accuracy: 0.9789 (97.9%)
Validation — Recall (macro):    0.9789
Validation — Recall (weighted): 0.9916
Validation — F1 (macro):        0.9818 (98.2%)
Validation — F1 (weighted):     0.9915
Validation — ROC AUC (macro):   0.9999

Test — Accuracy:          0.9748 (97.5%)
Test — Balanced accuracy: 0.9620 (96.2%)
Test — Recall (macro):    0.9620
Test — Recall (weighted): 0.9748
Test — F1 (macro):        0.9721 (97.2%)
Test — F1 (weighted):     0.9746
Test — ROC AUC (macro):   0.9998

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_onset,13,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_onset,18,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_onset,46,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589
3,rtbc_acrossyear_birdnet_onset,123,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.991597,...,0.981789,0.991489,0.999900,0.974790,0.961988,0.961988,0.974790,0.972057,0.974561,0.999780

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,onset,1024,4,0.966 ± 0.009,0.943 ± 0.041,0.9992 ± 0.0007

Seed set to 321

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'start_time', 'end_time', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_9/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │     0.827557384967804     │
│         test_loss         │    0.10659830272197723    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_onset/version_8/checkpoints/best-rtbc-acrossyear-birdnet_onset-epoch=08-val_f1=0.7652.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.8260229825973511     │
│         test_loss         │    0.13633236289024353    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1363
test_acc: 0.9552 (95.5%)
test_f1: 0.8260 (82.6%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     0.800     0.889         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.874     0.987     0.927        77
     LS3_2022-23      0.981     0.839     0.904        62
     LS6_2022-23      1.000     1.000     1.000        45
     PC2_2022-23      1.000     1.000     1.000        42
     PC3_2022-23      0.964     0.931     0.947        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.880     1.000     0.936        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.955       357
       macro avg      0.981     0.954     0.965       357
    weighted avg      0.959     0.955     0.955       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22        1.0  1.000000  1.000000     19.0
1  32PC1_2022-23        1.0  1.000000  1.000000     22.0
2     AL_2019-20        1.0  1.000000  1.000000      2.0
3     AL_2021-22        1.0  0.800000  0.888889      5.0
4    BUG_2021-22        1.0  0.833333  0.909091      6.0

Validation — Accuracy:          0.9552 (95.5%)
Validation — Balanced accuracy: 0.9737 (97.4%)
Validation — Recall (macro):    0.9737
Validation — Recall (weighted): 0.9552
Validation — F1 (macro):        0.9701 (97.0%)
Validation — F1 (weighted):     0.9553
Validation — ROC AUC (macro):   0.9997

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.9541 (95.4%)
Test — Recall (macro):    0.9541
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.9654 (96.5%)
Test — F1 (weighted):     0.9548
Test — ROC AUC (macro):   0.9985

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_onset,13,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_onset,18,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_onset,46,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589
3,rtbc_acrossyear_birdnet_onset,123,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.991597,...,0.981789,0.991489,0.999900,0.974790,0.961988,0.961988,0.974790,0.972057,0.974561,0.999780
4,rtbc_acrossyear_birdnet_onset,321,rtbc,acrossyear,birdnet,onset,1024,256,0.001,0.955182,...,0.970067,0.955254,0.999661,0.955182,0.954068,0.954068,0.955182,0.965377,0.954819,0.998531

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,onset,1024,5,0.964 ± 0.009,0.947 ± 0.037,0.9991 ± 0.0007

Seed set to 18

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_1/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7595635652542114     │
│         test_loss         │    0.11522399634122849    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_0/checkpoints/best-rtbc-acrossyear-birdnet_gap-epoch=05-val_f1=0.7511.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.6749309301376343     │
│         test_loss         │    0.1959298551082611     │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1959
test_acc: 0.9552 (95.5%)
test_f1: 0.6749 (67.5%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.900     0.947     0.923        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      0.000     0.000     0.000         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     1.000     1.000         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      0.800     0.800     0.800         5
     LS2_2022-23      0.986     0.909     0.946        77
     LS3_2022-23      0.938     0.984     0.961        62
     LS6_2022-23      1.000     0.978     0.989        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      0.848     0.966     0.903        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.955       357
       macro avg      0.889     0.889     0.886       357
    weighted avg      0.953     0.955     0.953       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.900000  0.947368  0.923077     19.0
1  32PC1_2022-23   1.000000  1.000000  1.000000     22.0
2     AL_2019-20   0.000000  0.000000  0.000000      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  1.000000  1.000000      6.0

Validation — Accuracy:          0.9496 (95.0%)
Validation — Balanced accuracy: 0.8706 (87.1%)
Validation — Recall (macro):    0.8706
Validation — Recall (weighted): 0.9496
Validation — F1 (macro):        0.8776 (87.8%)
Validation — F1 (weighted):     0.9477
Validation — ROC AUC (macro):   0.9979

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.8892 (88.9%)
Test — Recall (macro):    0.8892
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.8860 (88.6%)
Test — F1 (weighted):     0.9527
Test — ROC AUC (macro):   0.9993

Metrics file created: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_gap,18,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.94958,...,0.877584,0.94771,0.99792,0.955182,0.889155,0.889155,0.955182,0.88595,0.952678,0.999303

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,gap,1024,1,0.955 ± nan,0.886 ± nan,0.9993 ± nan

Seed set to 13

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_3/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.8127990365028381     │
│         test_loss         │    0.09961488097906113    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_2/checkpoints/best-rtbc-acrossyear-birdnet_gap-epoch=08-val_f1=0.7656.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9719887971878052     │
│          test_f1          │    0.7677643895149231     │
│         test_loss         │    0.12641286849975586    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1264
test_acc: 0.9720 (97.2%)
test_f1: 0.7678 (76.8%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      0.952     0.909     0.930        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.962     0.987     0.974        77
     LS3_2022-23      0.984     0.984     0.984        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      0.976     0.976     0.976        42
     PC3_2022-23      0.966     0.966     0.966        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.913     0.955     0.933        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.972       357
       macro avg      0.983     0.966     0.974       357
    weighted avg      0.972     0.972     0.972       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   1.000000  1.000000  1.000000     19.0
1  32PC1_2022-23   0.952381  0.909091  0.930233     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   1.000000  0.833333  0.909091      6.0

Validation — Accuracy:          0.9664 (96.6%)
Validation — Balanced accuracy: 0.9315 (93.2%)
Validation — Recall (macro):    0.9315
Validation — Recall (weighted): 0.9664
Validation — F1 (macro):        0.9386 (93.9%)
Validation — F1 (weighted):     0.9661
Validation — ROC AUC (macro):   0.9998

Test — Accuracy:          0.9720 (97.2%)
Test — Balanced accuracy: 0.9664 (96.6%)
Test — Recall (macro):    0.9664
Test — Recall (weighted): 0.9720
Test — F1 (macro):        0.9740 (97.4%)
Test — F1 (weighted):     0.9718
Test — ROC AUC (macro):   0.9982

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_gap,13,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_gap,18,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,gap,1024,2,0.964 ± 0.012,0.930 ± 0.062,0.9987 ± 0.0008

Seed set to 46

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_5/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9691876769065857     │
│          test_f1          │    0.7935192584991455     │
│         test_loss         │    0.0993865430355072     │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_4/checkpoints/best-rtbc-acrossyear-birdnet_gap-epoch=12-val_f1=0.7819.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7728484272956848     │
│         test_loss         │    0.11982722580432892    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1198
test_acc: 0.9636 (96.4%)
test_f1: 0.7728 (77.3%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     0.955     0.977        22
      AL_2019-20      1.000     0.500     0.667         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      0.857     1.000     0.923         6
FOURBIRD_2021-22      0.875     0.875     0.875         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.917     1.000     0.957        77
     LS3_2022-23      0.967     0.952     0.959        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.952     0.976        42
     PC3_2022-23      1.000     0.897     0.945        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      1.000     1.000     1.000        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.964       357
       macro avg      0.971     0.923     0.939       357
    weighted avg      0.966     0.964     0.963       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.950000  1.000000  0.974359     19.0
1  32PC1_2022-23   1.000000  0.954545  0.976744     22.0
2     AL_2019-20   1.000000  0.500000  0.666667      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   0.857143  1.000000  0.923077      6.0

Validation — Accuracy:          0.9608 (96.1%)
Validation — Balanced accuracy: 0.9428 (94.3%)
Validation — Recall (macro):    0.9428
Validation — Recall (weighted): 0.9608
Validation — F1 (macro):        0.9528 (95.3%)
Validation — F1 (weighted):     0.9602
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9636 (96.4%)
Test — Balanced accuracy: 0.9234 (92.3%)
Test — Recall (macro):    0.9234
Test — Recall (weighted): 0.9636
Test — F1 (macro):        0.9394 (93.9%)
Test — F1 (weighted):     0.9630
Test — ROC AUC (macro):   0.9996

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_gap,13,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_gap,18,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_gap,46,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,gap,1024,3,0.964 ± 0.008,0.933 ± 0.044,0.9990 ± 0.0007

Seed set to 123

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=40` reached.

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_7/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.7991259694099426     │
│         test_loss         │    0.07716686278581619    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_6/checkpoints/best-rtbc-acrossyear-birdnet_gap-epoch=30-val_f1=0.9384.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.7991259694099426     │
│         test_loss         │    0.07332269102334976    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0733
test_acc: 0.9748 (97.5%)
test_f1: 0.7991 (79.9%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     0.800     0.889         5
     LS2_2022-23      0.962     0.974     0.968        77
     LS3_2022-23      0.984     0.968     0.976        62
     LS6_2022-23      0.978     1.000     0.989        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      0.933     0.966     0.949        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.975       357
       macro avg      0.985     0.962     0.972       357
    weighted avg      0.975     0.975     0.975       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22       0.95  1.000000  0.974359     19.0
1  32PC1_2022-23       1.00  1.000000  1.000000     22.0
2     AL_2019-20       1.00  1.000000  1.000000      2.0
3     AL_2021-22       1.00  1.000000  1.000000      5.0
4    BUG_2021-22       1.00  0.833333  0.909091      6.0

Validation — Accuracy:          0.9916 (99.2%)
Validation — Balanced accuracy: 0.9789 (97.9%)
Validation — Recall (macro):    0.9789
Validation — Recall (weighted): 0.9916
Validation — F1 (macro):        0.9818 (98.2%)
Validation — F1 (weighted):     0.9915
Validation — ROC AUC (macro):   0.9999

Test — Accuracy:          0.9748 (97.5%)
Test — Balanced accuracy: 0.9620 (96.2%)
Test — Recall (macro):    0.9620
Test — Recall (weighted): 0.9748
Test — F1 (macro):        0.9721 (97.2%)
Test — F1 (weighted):     0.9746
Test — ROC AUC (macro):   0.9998

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_gap,13,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_gap,18,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_gap,46,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589
3,rtbc_acrossyear_birdnet_gap,123,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.991597,...,0.981789,0.991489,0.999900,0.974790,0.961988,0.961988,0.974790,0.972057,0.974561,0.999780

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,gap,1024,4,0.966 ± 0.009,0.943 ± 0.041,0.9992 ± 0.0007

Seed set to 321

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: birdnet
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_3sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap_figures
EMBEDDING_DIM: 1024
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 2 parquet parts; first 3: ['part_0000.parquet', 'part_0001.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 266 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
266 K     Trainable params
0         Non-trainable params
266 K     Total params
1.066     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_9/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │     0.827557384967804     │
│         test_loss         │    0.10659830272197723    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_birdnet_gap/version_8/checkpoints/best-rtbc-acrossyear-birdnet_gap-epoch=08-val_f1=0.7652.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.8260229825973511     │
│         test_loss         │    0.13633236289024353    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1363
test_acc: 0.9552 (95.5%)
test_f1: 0.8260 (82.6%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     0.800     0.889         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.874     0.987     0.927        77
     LS3_2022-23      0.981     0.839     0.904        62
     LS6_2022-23      1.000     1.000     1.000        45
     PC2_2022-23      1.000     1.000     1.000        42
     PC3_2022-23      0.964     0.931     0.947        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.880     1.000     0.936        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.955       357
       macro avg      0.981     0.954     0.965       357
    weighted avg      0.959     0.955     0.955       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22        1.0  1.000000  1.000000     19.0
1  32PC1_2022-23        1.0  1.000000  1.000000     22.0
2     AL_2019-20        1.0  1.000000  1.000000      2.0
3     AL_2021-22        1.0  0.800000  0.888889      5.0
4    BUG_2021-22        1.0  0.833333  0.909091      6.0

Validation — Accuracy:          0.9552 (95.5%)
Validation — Balanced accuracy: 0.9737 (97.4%)
Validation — Recall (macro):    0.9737
Validation — Recall (weighted): 0.9552
Validation — F1 (macro):        0.9701 (97.0%)
Validation — F1 (weighted):     0.9553
Validation — ROC AUC (macro):   0.9997

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.9541 (95.4%)
Test — Recall (macro):    0.9541
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.9654 (96.5%)
Test — F1 (weighted):     0.9548
Test — ROC AUC (macro):   0.9985

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_birdnet_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_birdnet_gap,13,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.966387,...,0.938571,0.966052,0.999765,0.971989,0.966396,0.966396,0.971989,0.973982,0.971836,0.998192
1,rtbc_acrossyear_birdnet_gap,18,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.949580,...,0.877584,0.947710,0.997920,0.955182,0.889155,0.889155,0.955182,0.885950,0.952678,0.999303
2,rtbc_acrossyear_birdnet_gap,46,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.960784,...,0.952835,0.960227,0.999436,0.963585,0.923408,0.923408,0.963585,0.939410,0.963021,0.999589
3,rtbc_acrossyear_birdnet_gap,123,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.991597,...,0.981789,0.991489,0.999900,0.974790,0.961988,0.961988,0.974790,0.972057,0.974561,0.999780
4,rtbc_acrossyear_birdnet_gap,321,rtbc,acrossyear,birdnet,gap,1024,256,0.001,0.955182,...,0.970067,0.955254,0.999661,0.955182,0.954068,0.954068,0.955182,0.965377,0.954819,0.998531

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,birdnet,gap,1024,5,0.964 ± 0.009,0.947 ± 0.037,0.9991 ± 0.0007

Seed set to 18

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_onset_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'file_id', 'start_time', 'end_time', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_1/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9607843160629272     │
│          test_f1          │    0.7363066673278809     │
│         test_loss         │    0.11297193169593811    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_0/checkpoints/best-rtbc-acrossyear-perch_onset-epoch=12-val_f1=0.9008.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │    0.7991242408752441     │
│         test_loss         │    0.1370394378900528     │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1370
test_acc: 0.9664 (96.6%)
test_f1: 0.7991 (79.9%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.947     0.947     0.947        19
   32PC1_2022-23      0.917     1.000     0.957        22
      AL_2019-20      1.000     0.500     0.667         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     1.000     1.000         8
     LES_2017-18      1.000     0.667     0.800         3
     LS1_2021-22      1.000     0.800     0.889         5
     LS2_2022-23      0.927     0.987     0.956        77
     LS3_2022-23      0.983     0.935     0.959        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      1.000     1.000     1.000        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.966       357
       macro avg      0.974     0.904     0.928       357
    weighted avg      0.968     0.966     0.966       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.947368  0.947368  0.947368     19.0
1  32PC1_2022-23   0.916667  1.000000  0.956522     22.0
2     AL_2019-20   1.000000  0.500000  0.666667      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  1.000000  1.000000      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9569 (95.7%)
Validation — Recall (macro):    0.9569
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9592 (95.9%)
Validation — F1 (weighted):     0.9749
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9664 (96.6%)
Test — Balanced accuracy: 0.9036 (90.4%)
Test — Recall (macro):    0.9036
Test — Recall (weighted): 0.9664
Test — F1 (macro):        0.9281 (92.8%)
Test — F1 (weighted):     0.9656
Test — ROC AUC (macro):   0.9997

Metrics file created: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_onset,18,rtbc,acrossyear,perch,onset,1280,256,0.001,0.97479,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,onset,1280,1,0.966 ± nan,0.928 ± nan,0.9997 ± nan

Seed set to 13

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_onset_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'file_id', 'start_time', 'end_time', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_3/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │     0.755127489566803     │
│         test_loss         │    0.1460973471403122     │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_2/checkpoints/best-rtbc-acrossyear-perch_onset-epoch=26-val_f1=0.8406.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.7072843909263611     │
│         test_loss         │    0.15668801963329315    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1567
test_acc: 0.9552 (95.5%)
test_f1: 0.7073 (70.7%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     0.947     0.973        19
   32PC1_2022-23      0.957     1.000     0.978        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      0.800     0.667     0.727         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      0.800     0.800     0.800         5
     LS2_2022-23      0.906     1.000     0.951        77
     LS3_2022-23      1.000     0.919     0.958        62
     LS6_2022-23      0.957     1.000     0.978        45
     PC2_2022-23      0.976     0.952     0.964        42
     PC3_2022-23      1.000     0.931     0.964        29
Patience_2017-18      1.000     0.857     0.923         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.955       357
       macro avg      0.957     0.913     0.932       357
    weighted avg      0.957     0.955     0.955       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   1.000000  0.947368  0.972973     19.0
1  32PC1_2022-23   0.956522  1.000000  0.977778     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   0.800000  0.666667  0.727273      6.0

Validation — Accuracy:          0.9776 (97.8%)
Validation — Balanced accuracy: 0.9569 (95.7%)
Validation — Recall (macro):    0.9569
Validation — Recall (weighted): 0.9776
Validation — F1 (macro):        0.9619 (96.2%)
Validation — F1 (weighted):     0.9770
Validation — ROC AUC (macro):   0.9998

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.9135 (91.3%)
Test — Recall (macro):    0.9135
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.9316 (93.2%)
Test — F1 (weighted):     0.9546
Test — ROC AUC (macro):   0.9987

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_onset,13,rtbc,acrossyear,perch,onset,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_onset,18,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,onset,1280,2,0.961 ± 0.008,0.930 ± 0.003,0.9992 ± 0.0007

Seed set to 46

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_onset_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'file_id', 'start_time', 'end_time', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_5/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │    0.8043264150619507     │
│         test_loss         │    0.12860670685768127    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_4/checkpoints/best-rtbc-acrossyear-perch_onset-epoch=09-val_f1=0.8499.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9579831957817078     │
│          test_f1          │    0.8238705992698669     │
│         test_loss         │    0.15933053195476532    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1593
test_acc: 0.9580 (95.8%)
test_f1: 0.8239 (82.4%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     0.955     0.977        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.885     1.000     0.939        77
     LS3_2022-23      0.982     0.871     0.923        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.952     0.976        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      0.857     0.857     0.857         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.958       357
       macro avg      0.976     0.947     0.958       357
    weighted avg      0.961     0.958     0.958       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22       0.95  1.000000  0.974359     19.0
1  32PC1_2022-23       1.00  0.954545  0.976744     22.0
2     AL_2019-20       1.00  1.000000  1.000000      2.0
3     AL_2021-22       1.00  1.000000  1.000000      5.0
4    BUG_2021-22       1.00  1.000000  1.000000      6.0

Validation — Accuracy:          0.9692 (96.9%)
Validation — Balanced accuracy: 0.9327 (93.3%)
Validation — Recall (macro):    0.9327
Validation — Recall (weighted): 0.9692
Validation — F1 (macro):        0.9546 (95.5%)
Validation — F1 (weighted):     0.9683
Validation — ROC AUC (macro):   0.9995

Test — Accuracy:          0.9580 (95.8%)
Test — Balanced accuracy: 0.9472 (94.7%)
Test — Recall (macro):    0.9472
Test — Recall (weighted): 0.9580
Test — F1 (macro):        0.9584 (95.8%)
Test — F1 (weighted):     0.9577
Test — ROC AUC (macro):   0.9989

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_onset,13,rtbc,acrossyear,perch,onset,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_onset,18,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_onset,46,rtbc,acrossyear,perch,onset,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,onset,1280,3,0.960 ± 0.006,0.939 ± 0.017,0.9991 ± 0.0005

Seed set to 123

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_onset_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'file_id', 'start_time', 'end_time', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_7/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.8924623727798462     │
│         test_loss         │    0.07434167712926865    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_6/checkpoints/best-rtbc-acrossyear-perch_onset-epoch=18-val_f1=0.8244.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9691876769065857     │
│          test_f1          │    0.8463999032974243     │
│         test_loss         │    0.09476963430643082    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0948
test_acc: 0.9692 (96.9%)
test_f1: 0.8464 (84.6%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.973     0.922     0.947        77
     LS3_2022-23      0.912     1.000     0.954        62
     LS6_2022-23      1.000     0.978     0.989        45
     PC2_2022-23      0.953     0.976     0.965        42
     PC3_2022-23      1.000     0.931     0.964        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.969       357
       macro avg      0.987     0.980     0.983       357
    weighted avg      0.971     0.969     0.969       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.csv

      individual  precision  recall  f1-score  support
0  32PC1_2021-22        1.0     1.0       1.0     19.0
1  32PC1_2022-23        1.0     1.0       1.0     22.0
2     AL_2019-20        1.0     1.0       1.0      2.0
3     AL_2021-22        1.0     1.0       1.0      5.0
4    BUG_2021-22        1.0     1.0       1.0      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9613 (96.1%)
Validation — Recall (macro):    0.9613
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9707 (97.1%)
Validation — F1 (weighted):     0.9744
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9692 (96.9%)
Test — Balanced accuracy: 0.9801 (98.0%)
Test — Recall (macro):    0.9801
Test — Recall (weighted): 0.9692
Test — F1 (macro):        0.9831 (98.3%)
Test — F1 (weighted):     0.9691
Test — ROC AUC (macro):   0.9999

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_onset,13,rtbc,acrossyear,perch,onset,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_onset,18,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_onset,46,rtbc,acrossyear,perch,onset,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894
3,rtbc_acrossyear_perch_onset,123,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.970662,0.974354,0.999437,0.969188,0.980130,0.980130,0.969188,0.983086,0.969148,0.999864

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,onset,1280,4,0.962 ± 0.007,0.950 ± 0.026,0.9993 ± 0.0006

Seed set to 321

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: onset
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_onset_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied onset aggregation: kept the first embedding per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'file_id', 'start_time', 'end_time', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_9/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7709512114524841     │
│         test_loss         │    0.09498719125986099    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_onset/version_8/checkpoints/best-rtbc-acrossyear-perch_onset-epoch=28-val_f1=0.7887.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7407766580581665     │
│         test_loss         │    0.09939157217741013    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0994
test_acc: 0.9636 (96.4%)
test_f1: 0.7408 (74.1%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.947     0.947     0.947        19
   32PC1_2022-23      0.957     1.000     0.978        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     0.667     0.800         3
     LS1_2021-22      0.833     1.000     0.909         5
     LS2_2022-23      0.949     0.974     0.962        77
     LS3_2022-23      0.951     0.935     0.943        62
     LS6_2022-23      1.000     0.956     0.977        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.964       357
       macro avg      0.962     0.948     0.951       357
    weighted avg      0.965     0.964     0.963       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.947368  0.947368  0.947368     19.0
1  32PC1_2022-23   0.956522  1.000000  0.977778     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  0.833333  0.909091      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9627 (96.3%)
Validation — Recall (macro):    0.9627
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9724 (97.2%)
Validation — F1 (weighted):     0.9746
Validation — ROC AUC (macro):   0.9996

Test — Accuracy:          0.9636 (96.4%)
Test — Balanced accuracy: 0.9477 (94.8%)
Test — Recall (macro):    0.9477
Test — Recall (weighted): 0.9636
Test — F1 (macro):        0.9508 (95.1%)
Test — F1 (weighted):     0.9634
Test — ROC AUC (macro):   0.9992

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_onset_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_onset,13,rtbc,acrossyear,perch,onset,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_onset,18,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_onset,46,rtbc,acrossyear,perch,onset,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894
3,rtbc_acrossyear_perch_onset,123,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.970662,0.974354,0.999437,0.969188,0.980130,0.980130,0.969188,0.983086,0.969148,0.999864
4,rtbc_acrossyear_perch_onset,321,rtbc,acrossyear,perch,onset,1280,256,0.001,0.974790,...,0.972366,0.974579,0.999588,0.963585,0.947727,0.947727,0.963585,0.950758,0.963440,0.999230

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,onset,1280,5,0.962 ± 0.006,0.950 ± 0.022,0.9993 ± 0.0005

Seed set to 18

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_gap_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_1/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9607843160629272     │
│          test_f1          │    0.7363066673278809     │
│         test_loss         │    0.11297193169593811    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_0/checkpoints/best-rtbc-acrossyear-perch_gap-epoch=12-val_f1=0.9008.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │    0.7991242408752441     │
│         test_loss         │    0.1370394378900528     │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1370
test_acc: 0.9664 (96.6%)
test_f1: 0.7991 (79.9%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.947     0.947     0.947        19
   32PC1_2022-23      0.917     1.000     0.957        22
      AL_2019-20      1.000     0.500     0.667         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     1.000     1.000         8
     LES_2017-18      1.000     0.667     0.800         3
     LS1_2021-22      1.000     0.800     0.889         5
     LS2_2022-23      0.927     0.987     0.956        77
     LS3_2022-23      0.983     0.935     0.959        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      1.000     1.000     1.000        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.966       357
       macro avg      0.974     0.904     0.928       357
    weighted avg      0.968     0.966     0.966       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.947368  0.947368  0.947368     19.0
1  32PC1_2022-23   0.916667  1.000000  0.956522     22.0
2     AL_2019-20   1.000000  0.500000  0.666667      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  1.000000  1.000000      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9569 (95.7%)
Validation — Recall (macro):    0.9569
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9592 (95.9%)
Validation — F1 (weighted):     0.9749
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9664 (96.6%)
Test — Balanced accuracy: 0.9036 (90.4%)
Test — Recall (macro):    0.9036
Test — Recall (weighted): 0.9664
Test — F1 (macro):        0.9281 (92.8%)
Test — F1 (weighted):     0.9656
Test — ROC AUC (macro):   0.9997

Metrics file created: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_gap,18,rtbc,acrossyear,perch,gap,1280,256,0.001,0.97479,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,gap,1280,1,0.966 ± nan,0.928 ± nan,0.9997 ± nan

Seed set to 13

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_gap_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      17    5     6
7      15    5     5
3      14    5     5
6      11    4     3
15     10    4     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_3/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │     0.755127489566803     │
│         test_loss         │    0.1460973471403122     │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_2/checkpoints/best-rtbc-acrossyear-perch_gap-epoch=26-val_f1=0.8406.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9551820755004883     │
│          test_f1          │    0.7072843909263611     │
│         test_loss         │    0.15668801963329315    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1567
test_acc: 0.9552 (95.5%)
test_f1: 0.7073 (70.7%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     0.947     0.973        19
   32PC1_2022-23      0.957     1.000     0.978        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      0.800     0.667     0.727         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      0.800     0.800     0.800         5
     LS2_2022-23      0.906     1.000     0.951        77
     LS3_2022-23      1.000     0.919     0.958        62
     LS6_2022-23      0.957     1.000     0.978        45
     PC2_2022-23      0.976     0.952     0.964        42
     PC3_2022-23      1.000     0.931     0.964        29
Patience_2017-18      1.000     0.857     0.923         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.955       357
       macro avg      0.957     0.913     0.932       357
    weighted avg      0.957     0.955     0.955       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   1.000000  0.947368  0.972973     19.0
1  32PC1_2022-23   0.956522  1.000000  0.977778     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   1.000000  1.000000  1.000000      5.0
4    BUG_2021-22   0.800000  0.666667  0.727273      6.0

Validation — Accuracy:          0.9776 (97.8%)
Validation — Balanced accuracy: 0.9569 (95.7%)
Validation — Recall (macro):    0.9569
Validation — Recall (weighted): 0.9776
Validation — F1 (macro):        0.9619 (96.2%)
Validation — F1 (weighted):     0.9770
Validation — ROC AUC (macro):   0.9998

Test — Accuracy:          0.9552 (95.5%)
Test — Balanced accuracy: 0.9135 (91.3%)
Test — Recall (macro):    0.9135
Test — Recall (weighted): 0.9552
Test — F1 (macro):        0.9316 (93.2%)
Test — F1 (weighted):     0.9546
Test — ROC AUC (macro):   0.9987

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_gap,13,rtbc,acrossyear,perch,gap,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_gap,18,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,gap,1280,2,0.961 ± 0.008,0.930 ± 0.003,0.9992 ± 0.0007

Seed set to 46

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_gap_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_5/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9663865566253662     │
│          test_f1          │    0.8043264150619507     │
│         test_loss         │    0.12860670685768127    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_4/checkpoints/best-rtbc-acrossyear-perch_gap-epoch=09-val_f1=0.8499.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9579831957817078     │
│          test_f1          │    0.8238705992698669     │
│         test_loss         │    0.15933053195476532    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.1593
test_acc: 0.9580 (95.8%)
test_f1: 0.8239 (82.4%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.950     1.000     0.974        19
   32PC1_2022-23      1.000     0.955     0.977        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.885     1.000     0.939        77
     LS3_2022-23      0.982     0.871     0.923        62
     LS6_2022-23      0.978     0.978     0.978        45
     PC2_2022-23      1.000     0.952     0.976        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      0.857     0.857     0.857         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     0.667     0.800         3

        accuracy                          0.958       357
       macro avg      0.976     0.947     0.958       357
    weighted avg      0.961     0.958     0.958       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22       0.95  1.000000  0.974359     19.0
1  32PC1_2022-23       1.00  0.954545  0.976744     22.0
2     AL_2019-20       1.00  1.000000  1.000000      2.0
3     AL_2021-22       1.00  1.000000  1.000000      5.0
4    BUG_2021-22       1.00  1.000000  1.000000      6.0

Validation — Accuracy:          0.9692 (96.9%)
Validation — Balanced accuracy: 0.9327 (93.3%)
Validation — Recall (macro):    0.9327
Validation — Recall (weighted): 0.9692
Validation — F1 (macro):        0.9546 (95.5%)
Validation — F1 (weighted):     0.9683
Validation — ROC AUC (macro):   0.9995

Test — Accuracy:          0.9580 (95.8%)
Test — Balanced accuracy: 0.9472 (94.7%)
Test — Recall (macro):    0.9472
Test — Recall (weighted): 0.9580
Test — F1 (macro):        0.9584 (95.8%)
Test — F1 (weighted):     0.9577
Test — ROC AUC (macro):   0.9989

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_gap,13,rtbc,acrossyear,perch,gap,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_gap,18,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_gap,46,rtbc,acrossyear,perch,gap,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,gap,1280,3,0.960 ± 0.006,0.939 ± 0.017,0.9991 ± 0.0005

Seed set to 123

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_gap_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_7/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9747899174690247     │
│          test_f1          │    0.8924623727798462     │
│         test_loss         │    0.07434167712926865    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_6/checkpoints/best-rtbc-acrossyear-perch_gap-epoch=18-val_f1=0.8244.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9691876769065857     │
│          test_f1          │    0.8463999032974243     │
│         test_loss         │    0.09476963430643082    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0948
test_acc: 0.9692 (96.9%)
test_f1: 0.8464 (84.6%)
                  precision    recall  f1-score   support

   32PC1_2021-22      1.000     1.000     1.000        19
   32PC1_2022-23      1.000     1.000     1.000        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      1.000     1.000     1.000         5
     BUG_2021-22      1.000     1.000     1.000         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     1.000     1.000         3
     LS1_2021-22      1.000     1.000     1.000         5
     LS2_2022-23      0.973     0.922     0.947        77
     LS3_2022-23      0.912     1.000     0.954        62
     LS6_2022-23      1.000     0.978     0.989        45
     PC2_2022-23      0.953     0.976     0.965        42
     PC3_2022-23      1.000     0.931     0.964        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.957     1.000     0.978        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.969       357
       macro avg      0.987     0.980     0.983       357
    weighted avg      0.971     0.969     0.969       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.csv

      individual  precision  recall  f1-score  support
0  32PC1_2021-22        1.0     1.0       1.0     19.0
1  32PC1_2022-23        1.0     1.0       1.0     22.0
2     AL_2019-20        1.0     1.0       1.0      2.0
3     AL_2021-22        1.0     1.0       1.0      5.0
4    BUG_2021-22        1.0     1.0       1.0      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9613 (96.1%)
Validation — Recall (macro):    0.9613
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9707 (97.1%)
Validation — F1 (weighted):     0.9744
Validation — ROC AUC (macro):   0.9994

Test — Accuracy:          0.9692 (96.9%)
Test — Balanced accuracy: 0.9801 (98.0%)
Test — Recall (macro):    0.9801
Test — Recall (weighted): 0.9692
Test — F1 (macro):        0.9831 (98.3%)
Test — F1 (weighted):     0.9691
Test — ROC AUC (macro):   0.9999

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_gap,13,rtbc,acrossyear,perch,gap,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_gap,18,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_gap,46,rtbc,acrossyear,perch,gap,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894
3,rtbc_acrossyear_perch_gap,123,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.970662,0.974354,0.999437,0.969188,0.980130,0.980130,0.969188,0.983086,0.969148,0.999864

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,gap,1280,4,0.962 ± 0.007,0.950 ± 0.026,0.9993 ± 0.0006

Seed set to 321

DATASET_NAME: rtbc
SPLIT_TYPE: acrossyear
MODEL: perch
AGGREGATION: gap
PARTS_DIR: /teamspace/studios/this_studio/Output_files/Embeddings_from_5sPadding/rtbc_parquet_parts
TRN_CSV: /teamspace/studios/this_studio/Output_metadata/rtbc_metadata/rtbc_metadata.csv
TST_CSV: None
LOG_DIR: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap
METRICS_FILE: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv
FIGURES_DIR: /teamspace/studios/this_studio/Results/rtbc/acrossyear/rtbc_acrossyear_perch_gap_figures
EMBEDDING_DIM: 1280
[Single-label schema] Using 'class' as labels.
Loaded 1,785 label rows; unique labeled audio files: 1,785
Example mapping: [('32pc1_2022-23_57.wav', '32PC1_2022-23'), ('32pc1_2022-23_0.wav', '32PC1_2022-23'), ('32pc1_2022-23_74.wav', '32PC1_2022-23')]
Found 1 parquet parts; first 3: ['part_0000.parquet']
Rows before aggregation: 1,785
Unique files before aggregation: 1,785
Applied GAP aggregation: averaged embeddings per file.
Rows after aggregation: 1,785
Unique files after aggregation: 1,785
Final columns: ['file_name', 'label', 'dim_0', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5', 'dim_6', 'dim_7', 'dim_8', 'dim_9', 'dim_10', 'dim_11', 'dim_12', 'dim_13', 'dim_14', 'dim_15', 'dim_16', 'dim_17', 'dim_18', 'dim_19', 'dim_20', 'dim_21', 'dim_22', 'dim_23', 'dim_24', 'dim_25', 'dim_26', 'dim_27', 'dim_28', 'dim_29', 'dim_30', 'dim_31', 'dim_32', 'dim_33', 'dim_34', 'dim_35', 'dim_36', 'dim_37', 'dim_38', 'dim_39', 'dim_40', 'dim_41', 'dim_42', 'dim_43', 'dim_44', 'dim_45', 'dim_46', 'dim_47', 'dim_48', 'dim_49', 'dim_50', 'dim_51', 'dim_52', 'dim_53', 'dim_54', 'dim_55', 'dim_56', 'dim_57', 'dim_58', 'dim_59', 'dim_60', 'dim_61', 'dim_62', 'dim_63', 'dim_64', 'dim_65', 'dim_66', 'dim_67', 'dim_68', 'dim_69', 'dim_70', 'dim_71', 'dim_72', 'dim_73', 'dim_74', 'dim_75', 'dim_76', 'dim_77', 'dim_78', 'dim_79', 'dim_80', 'dim_81', 'dim_82', 'dim_83', 'dim_84', 'dim_85', 'dim_86', 'dim_87', 'dim_88', 'dim_89', 'dim_90', 'dim_91', 'dim_92', 'dim_93', 'dim_94', 'dim_95', 'dim_96', 'dim_97', 'dim_98', 'dim_99', 'dim_100', 'dim_101', 'dim_102', 'dim_103', 'dim_104', 'dim_105', 'dim_106', 'dim_107', 'dim_108', 'dim_109', 'dim_110', 'dim_111', 'dim_112', 'dim_113', 'dim_114', 'dim_115', 'dim_116', 'dim_117', 'dim_118', 'dim_119', 'dim_120', 'dim_121', 'dim_122', 'dim_123', 'dim_124', 'dim_125', 'dim_126', 'dim_127', 'dim_128', 'dim_129', 'dim_130', 'dim_131', 'dim_132', 'dim_133', 'dim_134', 'dim_135', 'dim_136', 'dim_137', 'dim_138', 'dim_139', 'dim_140', 'dim_141', 'dim_142', 'dim_143', 'dim_144', 'dim_145', 'dim_146', 'dim_147', 'dim_148', 'dim_149', 'dim_150', 'dim_151', 'dim_152', 'dim_153', 'dim_154', 'dim_155', 'dim_156', 'dim_157', 'dim_158', 'dim_159', 'dim_160', 'dim_161', 'dim_162', 'dim_163', 'dim_164', 'dim_165', 'dim_166', 'dim_167', 'dim_168', 'dim_169', 'dim_170', 'dim_171', 'dim_172', 'dim_173', 'dim_174', 'dim_175', 'dim_176', 'dim_177', 'dim_178', 'dim_179', 'dim_180', 'dim_181', 'dim_182', 'dim_183', 'dim_184', 'dim_185', 'dim_186', 'dim_187', 'dim_188', 'dim_189', 'dim_190', 'dim_191', 'dim_192', 'dim_193', 'dim_194', 'dim_195', 'dim_196', 'dim_197', 'dim_198', 'dim_199', 'dim_200', 'dim_201', 'dim_202', 'dim_203', 'dim_204', 'dim_205', 'dim_206', 'dim_207', 'dim_208', 'dim_209', 'dim_210', 'dim_211', 'dim_212', 'dim_213', 'dim_214', 'dim_215', 'dim_216', 'dim_217', 'dim_218', 'dim_219', 'dim_220', 'dim_221', 'dim_222', 'dim_223', 'dim_224', 'dim_225', 'dim_226', 'dim_227', 'dim_228', 'dim_229', 'dim_230', 'dim_231', 'dim_232', 'dim_233', 'dim_234', 'dim_235', 'dim_236', 'dim_237', 'dim_238', 'dim_239', 'dim_240', 'dim_241', 'dim_242', 'dim_243', 'dim_244', 'dim_245', 'dim_246', 'dim_247', 'dim_248', 'dim_249', 'dim_250', 'dim_251', 'dim_252', 'dim_253', 'dim_254', 'dim_255', 'dim_256', 'dim_257', 'dim_258', 'dim_259', 'dim_260', 'dim_261', 'dim_262', 'dim_263', 'dim_264', 'dim_265', 'dim_266', 'dim_267', 'dim_268', 'dim_269', 'dim_270', 'dim_271', 'dim_272', 'dim_273', 'dim_274', 'dim_275', 'dim_276', 'dim_277', 'dim_278', 'dim_279', 'dim_280', 'dim_281', 'dim_282', 'dim_283', 'dim_284', 'dim_285', 'dim_286', 'dim_287', 'dim_288', 'dim_289', 'dim_290', 'dim_291', 'dim_292', 'dim_293', 'dim_294', 'dim_295', 'dim_296', 'dim_297', 'dim_298', 'dim_299', 'dim_300', 'dim_301', 'dim_302', 'dim_303', 'dim_304', 'dim_305', 'dim_306', 'dim_307', 'dim_308', 'dim_309', 'dim_310', 'dim_311', 'dim_312', 'dim_313', 'dim_314', 'dim_315', 'dim_316', 'dim_317', 'dim_318', 'dim_319', 'dim_320', 'dim_321', 'dim_322', 'dim_323', 'dim_324', 'dim_325', 'dim_326', 'dim_327', 'dim_328', 'dim_329', 'dim_330', 'dim_331', 'dim_332', 'dim_333', 'dim_334', 'dim_335', 'dim_336', 'dim_337', 'dim_338', 'dim_339', 'dim_340', 'dim_341', 'dim_342', 'dim_343', 'dim_344', 'dim_345', 'dim_346', 'dim_347', 'dim_348', 'dim_349', 'dim_350', 'dim_351', 'dim_352', 'dim_353', 'dim_354', 'dim_355', 'dim_356', 'dim_357', 'dim_358', 'dim_359', 'dim_360', 'dim_361', 'dim_362', 'dim_363', 'dim_364', 'dim_365', 'dim_366', 'dim_367', 'dim_368', 'dim_369', 'dim_370', 'dim_371', 'dim_372', 'dim_373', 'dim_374', 'dim_375', 'dim_376', 'dim_377', 'dim_378', 'dim_379', 'dim_380', 'dim_381', 'dim_382', 'dim_383', 'dim_384', 'dim_385', 'dim_386', 'dim_387', 'dim_388', 'dim_389', 'dim_390', 'dim_391', 'dim_392', 'dim_393', 'dim_394', 'dim_395', 'dim_396', 'dim_397', 'dim_398', 'dim_399', 'dim_400', 'dim_401', 'dim_402', 'dim_403', 'dim_404', 'dim_405', 'dim_406', 'dim_407', 'dim_408', 'dim_409', 'dim_410', 'dim_411', 'dim_412', 'dim_413', 'dim_414', 'dim_415', 'dim_416', 'dim_417', 'dim_418', 'dim_419', 'dim_420', 'dim_421', 'dim_422', 'dim_423', 'dim_424', 'dim_425', 'dim_426', 'dim_427', 'dim_428', 'dim_429', 'dim_430', 'dim_431', 'dim_432', 'dim_433', 'dim_434', 'dim_435', 'dim_436', 'dim_437', 'dim_438', 'dim_439', 'dim_440', 'dim_441', 'dim_442', 'dim_443', 'dim_444', 'dim_445', 'dim_446', 'dim_447', 'dim_448', 'dim_449', 'dim_450', 'dim_451', 'dim_452', 'dim_453', 'dim_454', 'dim_455', 'dim_456', 'dim_457', 'dim_458', 'dim_459', 'dim_460', 'dim_461', 'dim_462', 'dim_463', 'dim_464', 'dim_465', 'dim_466', 'dim_467', 'dim_468', 'dim_469', 'dim_470', 'dim_471', 'dim_472', 'dim_473', 'dim_474', 'dim_475', 'dim_476', 'dim_477', 'dim_478', 'dim_479', 'dim_480', 'dim_481', 'dim_482', 'dim_483', 'dim_484', 'dim_485', 'dim_486', 'dim_487', 'dim_488', 'dim_489', 'dim_490', 'dim_491', 'dim_492', 'dim_493', 'dim_494', 'dim_495', 'dim_496', 'dim_497', 'dim_498', 'dim_499', 'dim_500', 'dim_501', 'dim_502', 'dim_503', 'dim_504', 'dim_505', 'dim_506', 'dim_507', 'dim_508', 'dim_509', 'dim_510', 'dim_511', 'dim_512', 'dim_513', 'dim_514', 'dim_515', 'dim_516', 'dim_517', 'dim_518', 'dim_519', 'dim_520', 'dim_521', 'dim_522', 'dim_523', 'dim_524', 'dim_525', 'dim_526', 'dim_527', 'dim_528', 'dim_529', 'dim_530', 'dim_531', 'dim_532', 'dim_533', 'dim_534', 'dim_535', 'dim_536', 'dim_537', 'dim_538', 'dim_539', 'dim_540', 'dim_541', 'dim_542', 'dim_543', 'dim_544', 'dim_545', 'dim_546', 'dim_547', 'dim_548', 'dim_549', 'dim_550', 'dim_551', 'dim_552', 'dim_553', 'dim_554', 'dim_555', 'dim_556', 'dim_557', 'dim_558', 'dim_559', 'dim_560', 'dim_561', 'dim_562', 'dim_563', 'dim_564', 'dim_565', 'dim_566', 'dim_567', 'dim_568', 'dim_569', 'dim_570', 'dim_571', 'dim_572', 'dim_573', 'dim_574', 'dim_575', 'dim_576', 'dim_577', 'dim_578', 'dim_579', 'dim_580', 'dim_581', 'dim_582', 'dim_583', 'dim_584', 'dim_585', 'dim_586', 'dim_587', 'dim_588', 'dim_589', 'dim_590', 'dim_591', 'dim_592', 'dim_593', 'dim_594', 'dim_595', 'dim_596', 'dim_597', 'dim_598', 'dim_599', 'dim_600', 'dim_601', 'dim_602', 'dim_603', 'dim_604', 'dim_605', 'dim_606', 'dim_607', 'dim_608', 'dim_609', 'dim_610', 'dim_611', 'dim_612', 'dim_613', 'dim_614', 'dim_615', 'dim_616', 'dim_617', 'dim_618', 'dim_619', 'dim_620', 'dim_621', 'dim_622', 'dim_623', 'dim_624', 'dim_625', 'dim_626', 'dim_627', 'dim_628', 'dim_629', 'dim_630', 'dim_631', 'dim_632', 'dim_633', 'dim_634', 'dim_635', 'dim_636', 'dim_637', 'dim_638', 'dim_639', 'dim_640', 'dim_641', 'dim_642', 'dim_643', 'dim_644', 'dim_645', 'dim_646', 'dim_647', 'dim_648', 'dim_649', 'dim_650', 'dim_651', 'dim_652', 'dim_653', 'dim_654', 'dim_655', 'dim_656', 'dim_657', 'dim_658', 'dim_659', 'dim_660', 'dim_661', 'dim_662', 'dim_663', 'dim_664', 'dim_665', 'dim_666', 'dim_667', 'dim_668', 'dim_669', 'dim_670', 'dim_671', 'dim_672', 'dim_673', 'dim_674', 'dim_675', 'dim_676', 'dim_677', 'dim_678', 'dim_679', 'dim_680', 'dim_681', 'dim_682', 'dim_683', 'dim_684', 'dim_685', 'dim_686', 'dim_687', 'dim_688', 'dim_689', 'dim_690', 'dim_691', 'dim_692', 'dim_693', 'dim_694', 'dim_695', 'dim_696', 'dim_697', 'dim_698', 'dim_699', 'dim_700', 'dim_701', 'dim_702', 'dim_703', 'dim_704', 'dim_705', 'dim_706', 'dim_707', 'dim_708', 'dim_709', 'dim_710', 'dim_711', 'dim_712', 'dim_713', 'dim_714', 'dim_715', 'dim_716', 'dim_717', 'dim_718', 'dim_719', 'dim_720', 'dim_721', 'dim_722', 'dim_723', 'dim_724', 'dim_725', 'dim_726', 'dim_727', 'dim_728', 'dim_729', 'dim_730', 'dim_731', 'dim_732', 'dim_733', 'dim_734', 'dim_735', 'dim_736', 'dim_737', 'dim_738', 'dim_739', 'dim_740', 'dim_741', 'dim_742', 'dim_743', 'dim_744', 'dim_745', 'dim_746', 'dim_747', 'dim_748', 'dim_749', 'dim_750', 'dim_751', 'dim_752', 'dim_753', 'dim_754', 'dim_755', 'dim_756', 'dim_757', 'dim_758', 'dim_759', 'dim_760', 'dim_761', 'dim_762', 'dim_763', 'dim_764', 'dim_765', 'dim_766', 'dim_767', 'dim_768', 'dim_769', 'dim_770', 'dim_771', 'dim_772', 'dim_773', 'dim_774', 'dim_775', 'dim_776', 'dim_777', 'dim_778', 'dim_779', 'dim_780', 'dim_781', 'dim_782', 'dim_783', 'dim_784', 'dim_785', 'dim_786', 'dim_787', 'dim_788', 'dim_789', 'dim_790', 'dim_791', 'dim_792', 'dim_793', 'dim_794', 'dim_795', 'dim_796', 'dim_797', 'dim_798', 'dim_799', 'dim_800', 'dim_801', 'dim_802', 'dim_803', 'dim_804', 'dim_805', 'dim_806', 'dim_807', 'dim_808', 'dim_809', 'dim_810', 'dim_811', 'dim_812', 'dim_813', 'dim_814', 'dim_815', 'dim_816', 'dim_817', 'dim_818', 'dim_819', 'dim_820', 'dim_821', 'dim_822', 'dim_823', 'dim_824', 'dim_825', 'dim_826', 'dim_827', 'dim_828', 'dim_829', 'dim_830', 'dim_831', 'dim_832', 'dim_833', 'dim_834', 'dim_835', 'dim_836', 'dim_837', 'dim_838', 'dim_839', 'dim_840', 'dim_841', 'dim_842', 'dim_843', 'dim_844', 'dim_845', 'dim_846', 'dim_847', 'dim_848', 'dim_849', 'dim_850', 'dim_851', 'dim_852', 'dim_853', 'dim_854', 'dim_855', 'dim_856', 'dim_857', 'dim_858', 'dim_859', 'dim_860', 'dim_861', 'dim_862', 'dim_863', 'dim_864', 'dim_865', 'dim_866', 'dim_867', 'dim_868', 'dim_869', 'dim_870', 'dim_871', 'dim_872', 'dim_873', 'dim_874', 'dim_875', 'dim_876', 'dim_877', 'dim_878', 'dim_879', 'dim_880', 'dim_881', 'dim_882', 'dim_883', 'dim_884', 'dim_885', 'dim_886', 'dim_887', 'dim_888', 'dim_889', 'dim_890', 'dim_891', 'dim_892', 'dim_893', 'dim_894', 'dim_895', 'dim_896', 'dim_897', 'dim_898', 'dim_899', 'dim_900', 'dim_901', 'dim_902', 'dim_903', 'dim_904', 'dim_905', 'dim_906', 'dim_907', 'dim_908', 'dim_909', 'dim_910', 'dim_911', 'dim_912', 'dim_913', 'dim_914', 'dim_915', 'dim_916', 'dim_917', 'dim_918', 'dim_919', 'dim_920', 'dim_921', 'dim_922', 'dim_923', 'dim_924', 'dim_925', 'dim_926', 'dim_927', 'dim_928', 'dim_929', 'dim_930', 'dim_931', 'dim_932', 'dim_933', 'dim_934', 'dim_935', 'dim_936', 'dim_937', 'dim_938', 'dim_939', 'dim_940', 'dim_941', 'dim_942', 'dim_943', 'dim_944', 'dim_945', 'dim_946', 'dim_947', 'dim_948', 'dim_949', 'dim_950', 'dim_951', 'dim_952', 'dim_953', 'dim_954', 'dim_955', 'dim_956', 'dim_957', 'dim_958', 'dim_959', 'dim_960', 'dim_961', 'dim_962', 'dim_963', 'dim_964', 'dim_965', 'dim_966', 'dim_967', 'dim_968', 'dim_969', 'dim_970', 'dim_971', 'dim_972', 'dim_973', 'dim_974', 'dim_975', 'dim_976', 'dim_977', 'dim_978', 'dim_979', 'dim_980', 'dim_981', 'dim_982', 'dim_983', 'dim_984', 'dim_985', 'dim_986', 'dim_987', 'dim_988', 'dim_989', 'dim_990', 'dim_991', 'dim_992', 'dim_993', 'dim_994', 'dim_995', 'dim_996', 'dim_997', 'dim_998', 'dim_999', 'dim_1000', 'dim_1001', 'dim_1002', 'dim_1003', 'dim_1004', 'dim_1005', 'dim_1006', 'dim_1007', 'dim_1008', 'dim_1009', 'dim_1010', 'dim_1011', 'dim_1012', 'dim_1013', 'dim_1014', 'dim_1015', 'dim_1016', 'dim_1017', 'dim_1018', 'dim_1019', 'dim_1020', 'dim_1021', 'dim_1022', 'dim_1023', 'dim_1024', 'dim_1025', 'dim_1026', 'dim_1027', 'dim_1028', 'dim_1029', 'dim_1030', 'dim_1031', 'dim_1032', 'dim_1033', 'dim_1034', 'dim_1035', 'dim_1036', 'dim_1037', 'dim_1038', 'dim_1039', 'dim_1040', 'dim_1041', 'dim_1042', 'dim_1043', 'dim_1044', 'dim_1045', 'dim_1046', 'dim_1047', 'dim_1048', 'dim_1049', 'dim_1050', 'dim_1051', 'dim_1052', 'dim_1053', 'dim_1054', 'dim_1055', 'dim_1056', 'dim_1057', 'dim_1058', 'dim_1059', 'dim_1060', 'dim_1061', 'dim_1062', 'dim_1063', 'dim_1064', 'dim_1065', 'dim_1066', 'dim_1067', 'dim_1068', 'dim_1069', 'dim_1070', 'dim_1071', 'dim_1072', 'dim_1073', 'dim_1074', 'dim_1075', 'dim_1076', 'dim_1077', 'dim_1078', 'dim_1079', 'dim_1080', 'dim_1081', 'dim_1082', 'dim_1083', 'dim_1084', 'dim_1085', 'dim_1086', 'dim_1087', 'dim_1088', 'dim_1089', 'dim_1090', 'dim_1091', 'dim_1092', 'dim_1093', 'dim_1094', 'dim_1095', 'dim_1096', 'dim_1097', 'dim_1098', 'dim_1099', 'dim_1100', 'dim_1101', 'dim_1102', 'dim_1103', 'dim_1104', 'dim_1105', 'dim_1106', 'dim_1107', 'dim_1108', 'dim_1109', 'dim_1110', 'dim_1111', 'dim_1112', 'dim_1113', 'dim_1114', 'dim_1115', 'dim_1116', 'dim_1117', 'dim_1118', 'dim_1119', 'dim_1120', 'dim_1121', 'dim_1122', 'dim_1123', 'dim_1124', 'dim_1125', 'dim_1126', 'dim_1127', 'dim_1128', 'dim_1129', 'dim_1130', 'dim_1131', 'dim_1132', 'dim_1133', 'dim_1134', 'dim_1135', 'dim_1136', 'dim_1137', 'dim_1138', 'dim_1139', 'dim_1140', 'dim_1141', 'dim_1142', 'dim_1143', 'dim_1144', 'dim_1145', 'dim_1146', 'dim_1147', 'dim_1148', 'dim_1149', 'dim_1150', 'dim_1151', 'dim_1152', 'dim_1153', 'dim_1154', 'dim_1155', 'dim_1156', 'dim_1157', 'dim_1158', 'dim_1159', 'dim_1160', 'dim_1161', 'dim_1162', 'dim_1163', 'dim_1164', 'dim_1165', 'dim_1166', 'dim_1167', 'dim_1168', 'dim_1169', 'dim_1170', 'dim_1171', 'dim_1172', 'dim_1173', 'dim_1174', 'dim_1175', 'dim_1176', 'dim_1177', 'dim_1178', 'dim_1179', 'dim_1180', 'dim_1181', 'dim_1182', 'dim_1183', 'dim_1184', 'dim_1185', 'dim_1186', 'dim_1187', 'dim_1188', 'dim_1189', 'dim_1190', 'dim_1191', 'dim_1192', 'dim_1193', 'dim_1194', 'dim_1195', 'dim_1196', 'dim_1197', 'dim_1198', 'dim_1199', 'dim_1200', 'dim_1201', 'dim_1202', 'dim_1203', 'dim_1204', 'dim_1205', 'dim_1206', 'dim_1207', 'dim_1208', 'dim_1209', 'dim_1210', 'dim_1211', 'dim_1212', 'dim_1213', 'dim_1214', 'dim_1215', 'dim_1216', 'dim_1217', 'dim_1218', 'dim_1219', 'dim_1220', 'dim_1221', 'dim_1222', 'dim_1223', 'dim_1224', 'dim_1225', 'dim_1226', 'dim_1227', 'dim_1228', 'dim_1229', 'dim_1230', 'dim_1231', 'dim_1232', 'dim_1233', 'dim_1234', 'dim_1235', 'dim_1236', 'dim_1237', 'dim_1238', 'dim_1239', 'dim_1240', 'dim_1241', 'dim_1242', 'dim_1243', 'dim_1244', 'dim_1245', 'dim_1246', 'dim_1247', 'dim_1248', 'dim_1249', 'dim_1250', 'dim_1251', 'dim_1252', 'dim_1253', 'dim_1254', 'dim_1255', 'dim_1256', 'dim_1257', 'dim_1258', 'dim_1259', 'dim_1260', 'dim_1261', 'dim_1262', 'dim_1263', 'dim_1264', 'dim_1265', 'dim_1266', 'dim_1267', 'dim_1268', 'dim_1269', 'dim_1270', 'dim_1271', 'dim_1272', 'dim_1273', 'dim_1274', 'dim_1275', 'dim_1276', 'dim_1277', 'dim_1278', 'dim_1279']
Train: 1,071 rows
Validation: 357 rows
Test: 357 rows
Labels in TRN: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in VAL: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Labels in TST: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Encoded classes: ['32PC1_2021-22', '32PC1_2022-23', 'AL_2019-20', 'AL_2021-22', 'BUG_2021-22', 'FOURBIRD_2021-22', 'LES_2017-18', 'LS1_2021-22', 'LS2_2022-23', 'LS3_2022-23', 'LS6_2022-23', 'PC2_2022-23', 'PC3_2022-23', 'Patience_2017-18', 'STENCH_2022-23', 'W1_2020-21']
Train size: 1071
Validation size: 357
Test size: 357

    train  val  test
8     233   78    77
9     187   62    62
10    135   45    45
11    127   42    42
12     87   29    29
14     66   22    22
1      65   22    22
0      56   19    19
5      23    8     8
13     20    6     7
4      16    6     6
7      15    5     5
3      14    5     5
6      11    4     3
15     11    3     3
2       5    1     2

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

  | Name           | Type               | Params | Mode
--------------------------------------------------------------
0 | net            | Sequential         | 332 K  | train
1 | train_accuracy | MulticlassAccuracy | 0      | train
2 | val_accuracy   | MulticlassAccuracy | 0      | train
3 | test_accuracy  | MulticlassAccuracy | 0      | train
4 | val_f1         | MulticlassF1Score  | 0      | train
5 | test_f1        | MulticlassF1Score  | 0      | train
6 | criterion      | CrossEntropyLoss   | 0      | train
--------------------------------------------------------------
332 K     Trainable params
0         Non-trainable params
332 K     Total params
1.328     Total estimated model params size (MB)
11        Modules in train mode
0         Modules in eval mode

=== Dataset metrics (all splits combined) ===
Total vocalizations: 1785
Maximum vocalizations per individual: 388
Minimum vocalizations per individual: 8
Vocalizations per individual (mean ± SD): 111.6 ± 116.2
Vocalizations per individual (mean ± SD, rounded): 112 ± 116

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Reading metrics from: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_9/metrics.csv

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7709512114524841     │
│         test_loss         │    0.09498719125986099    │
└───────────────────────────┴───────────────────────────┘

Best model saved at: /teamspace/studios/this_studio/logs/rtbc/acrossyear/rtbc_acrossyear_perch_gap/version_8/checkpoints/best-rtbc-acrossyear-perch_gap-epoch=28-val_f1=0.7887.ckpt

Testing: |          | 0/? [00:00<?, ?it/s]

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test_acc          │    0.9635854363441467     │
│          test_f1          │    0.7407766580581665     │
│         test_loss         │    0.09939157217741013    │
└───────────────────────────┴───────────────────────────┘

Test Metrics:
test_loss: 0.0994
test_acc: 0.9636 (96.4%)
test_f1: 0.7408 (74.1%)
                  precision    recall  f1-score   support

   32PC1_2021-22      0.947     0.947     0.947        19
   32PC1_2022-23      0.957     1.000     0.978        22
      AL_2019-20      1.000     1.000     1.000         2
      AL_2021-22      0.833     1.000     0.909         5
     BUG_2021-22      1.000     0.833     0.909         6
FOURBIRD_2021-22      1.000     0.875     0.933         8
     LES_2017-18      1.000     0.667     0.800         3
     LS1_2021-22      0.833     1.000     0.909         5
     LS2_2022-23      0.949     0.974     0.962        77
     LS3_2022-23      0.951     0.935     0.943        62
     LS6_2022-23      1.000     0.956     0.977        45
     PC2_2022-23      1.000     0.976     0.988        42
     PC3_2022-23      1.000     1.000     1.000        29
Patience_2017-18      1.000     1.000     1.000         7
  STENCH_2022-23      0.917     1.000     0.957        22
      W1_2020-21      1.000     1.000     1.000         3

        accuracy                          0.964       357
       macro avg      0.962     0.948     0.951       357
    weighted avg      0.965     0.964     0.963       357


Saved classification report (txt) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.txt
Saved classification report (csv) to: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_test_classification_report.csv

      individual  precision    recall  f1-score  support
0  32PC1_2021-22   0.947368  0.947368  0.947368     19.0
1  32PC1_2022-23   0.956522  1.000000  0.977778     22.0
2     AL_2019-20   1.000000  1.000000  1.000000      2.0
3     AL_2021-22   0.833333  1.000000  0.909091      5.0
4    BUG_2021-22   1.000000  0.833333  0.909091      6.0

Validation — Accuracy:          0.9748 (97.5%)
Validation — Balanced accuracy: 0.9627 (96.3%)
Validation — Recall (macro):    0.9627
Validation — Recall (weighted): 0.9748
Validation — F1 (macro):        0.9724 (97.2%)
Validation — F1 (weighted):     0.9746
Validation — ROC AUC (macro):   0.9996

Test — Accuracy:          0.9636 (96.4%)
Test — Balanced accuracy: 0.9477 (94.8%)
Test — Recall (macro):    0.9477
Test — Recall (weighted): 0.9636
Test — F1 (macro):        0.9508 (95.1%)
Test — F1 (weighted):     0.9634
Test — ROC AUC (macro):   0.9992

Metrics file appended: /teamspace/studios/this_studio/Results/rtbc/acrossyear/Metrics/rtbc_acrossyear_perch_gap_final_metrics.csv

,run_name,seed,dataset_name,split_type,model,aggegration,embedding_dim,hidden_dim,learning_rate,val_accuracy,...,val_f1_macro,val_f1_weighted,val_roc_auc_macro,test_accuracy,test_balanced_accuracy,test_recall_macro,test_recall_weighted,test_f1_macro,test_f1_weighted,test_roc_auc_macro
0,rtbc_acrossyear_perch_gap,13,rtbc,acrossyear,perch,gap,1280,256,0.001,0.977591,...,0.961901,0.977025,0.999766,0.955182,0.913476,0.913476,0.955182,0.931622,0.954603,0.998718
1,rtbc_acrossyear_perch_gap,18,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.959225,0.974881,0.999375,0.966387,0.903573,0.903573,0.966387,0.928057,0.965571,0.999673
2,rtbc_acrossyear_perch_gap,46,rtbc,acrossyear,perch,gap,1280,256,0.001,0.969188,...,0.954585,0.968294,0.999501,0.957983,0.947155,0.947155,0.957983,0.958428,0.957676,0.998894
3,rtbc_acrossyear_perch_gap,123,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.970662,0.974354,0.999437,0.969188,0.980130,0.980130,0.969188,0.983086,0.969148,0.999864
4,rtbc_acrossyear_perch_gap,321,rtbc,acrossyear,perch,gap,1280,256,0.001,0.974790,...,0.972366,0.974579,0.999588,0.963585,0.947727,0.947727,0.963585,0.950758,0.963440,0.999230

Aggregate summary across seeds:

,dataset_name,split_type,model,aggegration_mode,embedding_dim,n_seeds,test_accuracy,test_f1_macro,test_roc_auc_macro
0,rtbc,acrossyear,perch,gap,1280,5,0.962 ± 0.006,0.950 ± 0.022,0.9993 ± 0.0005